/* NAILONG TOOLS registry — generated, do not edit by hand unless needed */
window.NT_REGISTRY = {
  "version": "148.027.00",
  "generated": true,
  "count": 257,
  "categories": [
    "Image Tools",
    "PDF Tools",
    "Video Tools",
    "Audio Tools",
    "Text Tools",
    "Developer Tools",
    "Security & Generator",
    "Calculator",
    "Business Tools",
    "Design Tools",
    "QR & Barcode",
    "Social Media Tools",
    "Date & Time",
    "Document Tools",
    "File Tools",
    "Education",
    "Productivity",
    "Utility",
    "AI Tools"
  ],
  "tools": [
    {
      "id": "image-compressor",
      "name": "Image Compressor",
      "category": "Image Tools",
      "description": "Compress images in your browser without uploading to a server.",
      "kind": "image-compress",
      "icon": "fa-solid fa-compress",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "compress optimize jpg png webp size"
    },
    {
      "id": "image-resizer",
      "name": "Image Resizer",
      "category": "Image Tools",
      "description": "Resize images to exact pixel dimensions.",
      "kind": "image-resize",
      "icon": "fa-solid fa-up-right-and-down-left-from-center",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "resize scale width height"
    },
    {
      "id": "image-cropper",
      "name": "Image Cropper",
      "category": "Image Tools",
      "description": "Crop an image to a custom area.",
      "kind": "image-crop",
      "icon": "fa-solid fa-crop",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "crop cut"
    },
    {
      "id": "image-rotator",
      "name": "Image Rotator",
      "category": "Image Tools",
      "description": "Rotate an image 90, 180, or 270 degrees.",
      "kind": "image-rotate",
      "icon": "fa-solid fa-rotate",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "rotate turn"
    },
    {
      "id": "image-flipper",
      "name": "Image Flipper",
      "category": "Image Tools",
      "description": "Flip an image horizontally or vertically.",
      "kind": "image-flip",
      "icon": "fa-solid fa-left-right",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "flip mirror"
    },
    {
      "id": "image-converter",
      "name": "Image Converter",
      "category": "Image Tools",
      "description": "Convert images between JPG, PNG, and WEBP.",
      "kind": "image-convert",
      "icon": "fa-solid fa-exchange-alt",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "convert format jpg png webp"
    },
    {
      "id": "jpg-to-png",
      "name": "JPG to PNG",
      "category": "Image Tools",
      "description": "Convert JPG images to PNG.",
      "kind": "image-convert",
      "icon": "fa-solid fa-file-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "jpg jpeg png"
    },
    {
      "id": "png-to-jpg",
      "name": "PNG to JPG",
      "category": "Image Tools",
      "description": "Convert PNG images to JPG.",
      "kind": "image-convert",
      "icon": "fa-solid fa-file-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "png jpg"
    },
    {
      "id": "jpg-to-webp",
      "name": "JPG to WEBP",
      "category": "Image Tools",
      "description": "Convert JPG images to WEBP.",
      "kind": "image-convert",
      "icon": "fa-solid fa-file-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "jpg webp"
    },
    {
      "id": "png-to-webp",
      "name": "PNG to WEBP",
      "category": "Image Tools",
      "description": "Convert PNG images to WEBP.",
      "kind": "image-convert",
      "icon": "fa-solid fa-file-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "png webp"
    },
    {
      "id": "webp-to-jpg",
      "name": "WEBP to JPG",
      "category": "Image Tools",
      "description": "Convert WEBP images to JPG.",
      "kind": "image-convert",
      "icon": "fa-solid fa-file-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "webp jpg"
    },
    {
      "id": "webp-to-png",
      "name": "WEBP to PNG",
      "category": "Image Tools",
      "description": "Convert WEBP images to PNG.",
      "kind": "image-convert",
      "icon": "fa-solid fa-file-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "webp png"
    },
    {
      "id": "image-to-base64",
      "name": "Image to Base64",
      "category": "Image Tools",
      "description": "Encode an image as a Base64 data URL.",
      "kind": "image-base64",
      "icon": "fa-solid fa-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "base64 encode"
    },
    {
      "id": "base64-to-image",
      "name": "Base64 to Image",
      "category": "Image Tools",
      "description": "Decode a Base64 string into an image file.",
      "kind": "base64-image",
      "icon": "fa-solid fa-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "base64 decode"
    },
    {
      "id": "image-blur",
      "name": "Image Blur",
      "category": "Image Tools",
      "description": "Apply blur to an image.",
      "kind": "image-filter",
      "icon": "fa-solid fa-droplet",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "blur filter"
    },
    {
      "id": "image-grayscale",
      "name": "Image Grayscale",
      "category": "Image Tools",
      "description": "Convert an image to grayscale.",
      "kind": "image-filter",
      "icon": "fa-solid fa-circle-half-stroke",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "gray black white"
    },
    {
      "id": "image-brightness",
      "name": "Image Brightness",
      "category": "Image Tools",
      "description": "Adjust image brightness.",
      "kind": "image-filter",
      "icon": "fa-solid fa-sun",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "bright dark"
    },
    {
      "id": "image-contrast",
      "name": "Image Contrast",
      "category": "Image Tools",
      "description": "Adjust image contrast.",
      "kind": "image-filter",
      "icon": "fa-solid fa-circle-adjust",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "contrast"
    },
    {
      "id": "image-saturation",
      "name": "Image Saturation",
      "category": "Image Tools",
      "description": "Adjust image saturation.",
      "kind": "image-filter",
      "icon": "fa-solid fa-palette",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "saturate color"
    },
    {
      "id": "image-sepia",
      "name": "Image Sepia",
      "category": "Image Tools",
      "description": "Apply a sepia tone to an image.",
      "kind": "image-filter",
      "icon": "fa-solid fa-camera-retro",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sepia vintage"
    },
    {
      "id": "image-invert",
      "name": "Image Invert",
      "category": "Image Tools",
      "description": "Invert image colors.",
      "kind": "image-filter",
      "icon": "fa-solid fa-circle-half-stroke",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "invert negative"
    },
    {
      "id": "image-watermark",
      "name": "Image Watermark",
      "category": "Image Tools",
      "description": "Add a text watermark to an image.",
      "kind": "image-watermark",
      "icon": "fa-solid fa-stamp",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "watermark text"
    },
    {
      "id": "image-text-overlay",
      "name": "Image Text Overlay",
      "category": "Image Tools",
      "description": "Overlay custom text on an image.",
      "kind": "image-watermark",
      "icon": "fa-solid fa-font",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "text overlay caption"
    },
    {
      "id": "image-dimension-checker",
      "name": "Image Dimension Checker",
      "category": "Image Tools",
      "description": "Check width, height, and aspect ratio.",
      "kind": "image-info",
      "icon": "fa-solid fa-ruler-combined",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "size dimension width height"
    },
    {
      "id": "image-file-size-checker",
      "name": "Image File Size Checker",
      "category": "Image Tools",
      "description": "Check image file size and type.",
      "kind": "image-info",
      "icon": "fa-solid fa-weight-scale",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "filesize kb mb"
    },
    {
      "id": "image-color-picker",
      "name": "Image Color Picker",
      "category": "Image Tools",
      "description": "Pick a color from an uploaded image.",
      "kind": "image-picker",
      "icon": "fa-solid fa-eye-dropper",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "color pick hex"
    },
    {
      "id": "image-border",
      "name": "Image Border Generator",
      "category": "Image Tools",
      "description": "Add a colored border around an image.",
      "kind": "image-border",
      "icon": "fa-solid fa-border-all",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "border frame"
    },
    {
      "id": "image-bg-color",
      "name": "Image Background Color",
      "category": "Image Tools",
      "description": "Place an image on a solid background color.",
      "kind": "image-bg",
      "icon": "fa-solid fa-fill-drip",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "background color"
    },
    {
      "id": "favicon-generator",
      "name": "Favicon Generator",
      "category": "Image Tools",
      "description": "Create a 32x32 and 16x16 favicon from an image.",
      "kind": "image-favicon",
      "icon": "fa-solid fa-star",
      "popular": false,
      "newest": true,
      "premium": false,
      "keywords": "favicon ico"
    },
    {
      "id": "image-aspect-ratio",
      "name": "Image Aspect Ratio Calculator",
      "category": "Image Tools",
      "description": "Calculate target size from an aspect ratio.",
      "kind": "calc-aspect",
      "icon": "fa-solid fa-crop-simple",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "aspect ratio 16:9"
    },
    {
      "id": "image-pixelate",
      "name": "Image Pixelate",
      "category": "Image Tools",
      "description": "Pixelate an image for a mosaic look.",
      "kind": "image-pixelate",
      "icon": "fa-solid fa-table-cells",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "pixel mosaic"
    },
    {
      "id": "image-rounded",
      "name": "Image Rounded Corners",
      "category": "Image Tools",
      "description": "Apply rounded corners to an image.",
      "kind": "image-round",
      "icon": "fa-solid fa-square",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "round corner"
    },
    {
      "id": "image-opacity",
      "name": "Image Opacity",
      "category": "Image Tools",
      "description": "Change image opacity.",
      "kind": "image-filter",
      "icon": "fa-solid fa-droplet",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "opacity transparent"
    },
    {
      "id": "screenshot-cropper",
      "name": "Screenshot Cropper",
      "category": "Image Tools",
      "description": "Crop screenshots quickly.",
      "kind": "image-crop",
      "icon": "fa-solid fa-scissors",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "screenshot crop"
    },
    {
      "id": "pdf-merge",
      "name": "PDF Merger",
      "category": "PDF Tools",
      "description": "Merge multiple PDF files into one.",
      "kind": "pdf-merge",
      "icon": "fa-solid fa-object-group",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "merge combine pdf"
    },
    {
      "id": "pdf-split",
      "name": "PDF Split",
      "category": "PDF Tools",
      "description": "Split a PDF into individual pages.",
      "kind": "pdf-split",
      "icon": "fa-solid fa-scissors",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "split pages"
    },
    {
      "id": "pdf-rotate",
      "name": "PDF Rotate",
      "category": "PDF Tools",
      "description": "Rotate all pages in a PDF.",
      "kind": "pdf-rotate",
      "icon": "fa-solid fa-rotate",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "rotate pdf"
    },
    {
      "id": "images-to-pdf",
      "name": "Images to PDF",
      "category": "PDF Tools",
      "description": "Combine images into a single PDF.",
      "kind": "images-pdf",
      "icon": "fa-solid fa-file-pdf",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "image pdf jpg png"
    },
    {
      "id": "pdf-info",
      "name": "PDF Information",
      "category": "PDF Tools",
      "description": "View page count and PDF metadata.",
      "kind": "pdf-info",
      "icon": "fa-solid fa-circle-info",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "info metadata pages"
    },
    {
      "id": "text-to-pdf",
      "name": "Text to PDF",
      "category": "PDF Tools",
      "description": "Convert plain text into a downloadable PDF.",
      "kind": "text-pdf",
      "icon": "fa-solid fa-file-lines",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "text pdf"
    },
    {
      "id": "pdf-page-extract",
      "name": "PDF Extract Pages",
      "category": "PDF Tools",
      "description": "Extract a page range into a new PDF.",
      "kind": "pdf-extract",
      "icon": "fa-solid fa-file-export",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "extract pages"
    },
    {
      "id": "pdf-size-checker",
      "name": "PDF Size Checker",
      "category": "PDF Tools",
      "description": "Check PDF file size and page count.",
      "kind": "pdf-info",
      "icon": "fa-solid fa-weight-hanging",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "size pdf"
    },
    {
      "id": "video-info",
      "name": "Video Information",
      "category": "Video Tools",
      "description": "Read duration, size, and type of a video file in the browser.",
      "kind": "media-info",
      "icon": "fa-solid fa-circle-info",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "video info metadata"
    },
    {
      "id": "video-thumbnail",
      "name": "Video Thumbnail Generator",
      "category": "Video Tools",
      "description": "Capture a thumbnail frame from a local video.",
      "kind": "video-thumb",
      "icon": "fa-solid fa-image",
      "popular": false,
      "newest": true,
      "premium": false,
      "keywords": "thumbnail frame capture"
    },
    {
      "id": "video-aspect-ratio",
      "name": "Video Aspect Ratio Calculator",
      "category": "Video Tools",
      "description": "Calculate video frame size from an aspect ratio.",
      "kind": "calc-aspect",
      "icon": "fa-solid fa-film",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "16:9 9:16"
    },
    {
      "id": "gif-info",
      "name": "GIF Information",
      "category": "Video Tools",
      "description": "Inspect GIF file size and type.",
      "kind": "file-info",
      "icon": "fa-solid fa-gift",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "gif info"
    },
    {
      "id": "audio-info",
      "name": "Audio File Information",
      "category": "Audio Tools",
      "description": "Read audio file size, type, and duration.",
      "kind": "media-info",
      "icon": "fa-solid fa-music",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "audio info"
    },
    {
      "id": "audio-volume-preview",
      "name": "Audio Volume Preview",
      "category": "Audio Tools",
      "description": "Preview a local audio file and adjust playback volume.",
      "kind": "audio-preview",
      "icon": "fa-solid fa-volume-high",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "volume preview"
    },
    {
      "id": "word-counter",
      "name": "Word Counter",
      "category": "Text Tools",
      "description": "Count words, characters, sentences, and paragraphs.",
      "kind": "text-stats",
      "icon": "fa-solid fa-calculator",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "word count character"
    },
    {
      "id": "character-counter",
      "name": "Character Counter",
      "category": "Text Tools",
      "description": "Count characters with and without spaces.",
      "kind": "text-stats",
      "icon": "fa-solid fa-font",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "character length"
    },
    {
      "id": "sentence-counter",
      "name": "Sentence Counter",
      "category": "Text Tools",
      "description": "Count sentences in text.",
      "kind": "text-stats",
      "icon": "fa-solid fa-align-left",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sentence"
    },
    {
      "id": "paragraph-counter",
      "name": "Paragraph Counter",
      "category": "Text Tools",
      "description": "Count paragraphs in text.",
      "kind": "text-stats",
      "icon": "fa-solid fa-paragraph",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "paragraph"
    },
    {
      "id": "text-cleaner",
      "name": "Text Cleaner",
      "category": "Text Tools",
      "description": "Normalize whitespace and clean extra spaces.",
      "kind": "text-clean",
      "icon": "fa-solid fa-broom",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "clean space"
    },
    {
      "id": "remove-duplicate-lines",
      "name": "Remove Duplicate Lines",
      "category": "Text Tools",
      "description": "Remove repeated lines from a list.",
      "kind": "text-unique",
      "icon": "fa-solid fa-clone",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "duplicate unique"
    },
    {
      "id": "sort-lines",
      "name": "Sort Lines",
      "category": "Text Tools",
      "description": "Sort lines alphabetically A-Z or Z-A.",
      "kind": "text-sort",
      "icon": "fa-solid fa-arrow-down-a-z",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sort alphabet"
    },
    {
      "id": "reverse-text",
      "name": "Reverse Text",
      "category": "Text Tools",
      "description": "Reverse characters in text.",
      "kind": "text-reverse",
      "icon": "fa-solid fa-left-right",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "reverse"
    },
    {
      "id": "uppercase-converter",
      "name": "Uppercase Converter",
      "category": "Text Tools",
      "description": "Convert text to UPPERCASE.",
      "kind": "text-case",
      "icon": "fa-solid fa-a",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "upper caps"
    },
    {
      "id": "lowercase-converter",
      "name": "Lowercase Converter",
      "category": "Text Tools",
      "description": "Convert text to lowercase.",
      "kind": "text-case",
      "icon": "fa-solid fa-a",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "lower"
    },
    {
      "id": "title-case",
      "name": "Title Case",
      "category": "Text Tools",
      "description": "Convert text to Title Case.",
      "kind": "text-case",
      "icon": "fa-solid fa-heading",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "title case"
    },
    {
      "id": "sentence-case",
      "name": "Sentence Case",
      "category": "Text Tools",
      "description": "Convert text to Sentence case.",
      "kind": "text-case",
      "icon": "fa-solid fa-align-left",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sentence case"
    },
    {
      "id": "remove-spaces",
      "name": "Remove Spaces",
      "category": "Text Tools",
      "description": "Remove all spaces from text.",
      "kind": "text-nospaces",
      "icon": "fa-solid fa-minus",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "space remove"
    },
    {
      "id": "remove-empty-lines",
      "name": "Remove Empty Lines",
      "category": "Text Tools",
      "description": "Delete blank lines from text.",
      "kind": "text-noempty",
      "icon": "fa-solid fa-grip-lines",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "empty lines"
    },
    {
      "id": "text-diff",
      "name": "Text Compare",
      "category": "Text Tools",
      "description": "Compare two texts side by side.",
      "kind": "text-diff",
      "icon": "fa-solid fa-code-compare",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "diff compare"
    },
    {
      "id": "text-to-slug",
      "name": "Text to Slug",
      "category": "Text Tools",
      "description": "Create a URL slug from text.",
      "kind": "text-slug",
      "icon": "fa-solid fa-link",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "slug url"
    },
    {
      "id": "lorem-ipsum",
      "name": "Lorem Ipsum Generator",
      "category": "Text Tools",
      "description": "Generate placeholder paragraphs.",
      "kind": "lorem",
      "icon": "fa-solid fa-align-justify",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "lorem ipsum dummy"
    },
    {
      "id": "random-text",
      "name": "Random Text Generator",
      "category": "Text Tools",
      "description": "Generate random words.",
      "kind": "rand-text",
      "icon": "fa-solid fa-shuffle",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "random words"
    },
    {
      "id": "morse-encoder",
      "name": "Morse Code Encoder",
      "category": "Text Tools",
      "description": "Encode text to Morse code.",
      "kind": "morse-enc",
      "icon": "fa-solid fa-ellipsis",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "morse"
    },
    {
      "id": "morse-decoder",
      "name": "Morse Code Decoder",
      "category": "Text Tools",
      "description": "Decode Morse code to text.",
      "kind": "morse-dec",
      "icon": "fa-solid fa-ellipsis",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "morse decode"
    },
    {
      "id": "text-to-binary",
      "name": "Text to Binary",
      "category": "Text Tools",
      "description": "Convert text to binary.",
      "kind": "bin-enc",
      "icon": "fa-solid fa-1",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "binary"
    },
    {
      "id": "binary-to-text",
      "name": "Binary to Text",
      "category": "Text Tools",
      "description": "Convert binary to text.",
      "kind": "bin-dec",
      "icon": "fa-solid fa-0",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "binary decode"
    },
    {
      "id": "rot13",
      "name": "ROT13",
      "category": "Text Tools",
      "description": "Encode or decode text with ROT13.",
      "kind": "rot13",
      "icon": "fa-solid fa-rotate",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "rot13 cipher"
    },
    {
      "id": "url-encoder",
      "name": "URL Encoder",
      "category": "Text Tools",
      "description": "Percent-encode a URL or string.",
      "kind": "url-enc",
      "icon": "fa-solid fa-percent",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "encode url"
    },
    {
      "id": "url-decoder",
      "name": "URL Decoder",
      "category": "Text Tools",
      "description": "Decode a percent-encoded string.",
      "kind": "url-dec",
      "icon": "fa-solid fa-percent",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "decode url"
    },
    {
      "id": "html-entity-encoder",
      "name": "HTML Entity Encoder",
      "category": "Text Tools",
      "description": "Encode special characters as HTML entities.",
      "kind": "html-enc",
      "icon": "fa-solid fa-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "html entity"
    },
    {
      "id": "html-entity-decoder",
      "name": "HTML Entity Decoder",
      "category": "Text Tools",
      "description": "Decode HTML entities to text.",
      "kind": "html-dec",
      "icon": "fa-solid fa-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "html entity"
    },
    {
      "id": "line-counter",
      "name": "Line Counter",
      "category": "Text Tools",
      "description": "Count the number of lines.",
      "kind": "text-stats",
      "icon": "fa-solid fa-list-ol",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "lines"
    },
    {
      "id": "repeat-text",
      "name": "Repeat Text",
      "category": "Text Tools",
      "description": "Repeat a string N times.",
      "kind": "text-repeat",
      "icon": "fa-solid fa-copy",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "repeat"
    },
    {
      "id": "extract-emails",
      "name": "Email Extractor",
      "category": "Text Tools",
      "description": "Extract email addresses from text.",
      "kind": "extract-email",
      "icon": "fa-solid fa-envelope",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "email extract"
    },
    {
      "id": "extract-urls",
      "name": "URL Extractor",
      "category": "Text Tools",
      "description": "Extract URLs from text.",
      "kind": "extract-url",
      "icon": "fa-solid fa-link",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "url extract"
    },
    {
      "id": "word-frequency",
      "name": "Word Frequency",
      "category": "Text Tools",
      "description": "Count how often each word appears.",
      "kind": "word-freq",
      "icon": "fa-solid fa-chart-simple",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "frequency"
    },
    {
      "id": "add-line-numbers",
      "name": "Add Line Numbers",
      "category": "Text Tools",
      "description": "Prefix each line with a number.",
      "kind": "line-num",
      "icon": "fa-solid fa-list-ol",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "line number"
    },
    {
      "id": "trim-lines",
      "name": "Trim Lines",
      "category": "Text Tools",
      "description": "Trim spaces on every line.",
      "kind": "trim-lines",
      "icon": "fa-solid fa-scissors",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "trim"
    },
    {
      "id": "camel-case",
      "name": "Camel Case Converter",
      "category": "Text Tools",
      "description": "Convert text to camelCase.",
      "kind": "text-case",
      "icon": "fa-solid fa-i-cursor",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "camelCase"
    },
    {
      "id": "snake-case",
      "name": "Snake Case Converter",
      "category": "Text Tools",
      "description": "Convert text to snake_case.",
      "kind": "text-case",
      "icon": "fa-solid fa-i-cursor",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "snake_case"
    },
    {
      "id": "kebab-case",
      "name": "Kebab Case Converter",
      "category": "Text Tools",
      "description": "Convert text to kebab-case.",
      "kind": "text-case",
      "icon": "fa-solid fa-i-cursor",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "kebab-case"
    },
    {
      "id": "json-formatter",
      "name": "JSON Formatter",
      "category": "Developer Tools",
      "description": "Format and pretty-print JSON.",
      "kind": "json-pretty",
      "icon": "fa-solid fa-brackets-curly",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "json format pretty"
    },
    {
      "id": "json-validator",
      "name": "JSON Validator",
      "category": "Developer Tools",
      "description": "Validate JSON and show errors.",
      "kind": "json-pretty",
      "icon": "fa-solid fa-check",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "json validate"
    },
    {
      "id": "json-minifier",
      "name": "JSON Minifier",
      "category": "Developer Tools",
      "description": "Minify JSON to one line.",
      "kind": "json-min",
      "icon": "fa-solid fa-minimize",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "json minify"
    },
    {
      "id": "xml-formatter",
      "name": "XML Formatter",
      "category": "Developer Tools",
      "description": "Pretty-print XML.",
      "kind": "xml-pretty",
      "icon": "fa-solid fa-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "xml format"
    },
    {
      "id": "html-formatter",
      "name": "HTML Formatter",
      "category": "Developer Tools",
      "description": "Indent HTML markup.",
      "kind": "html-pretty",
      "icon": "fa-solid fa-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "html format"
    },
    {
      "id": "html-minifier",
      "name": "HTML Minifier",
      "category": "Developer Tools",
      "description": "Minify HTML by removing extra space.",
      "kind": "html-min",
      "icon": "fa-solid fa-minimize",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "html minify"
    },
    {
      "id": "css-formatter",
      "name": "CSS Formatter",
      "category": "Developer Tools",
      "description": "Pretty-print CSS rules.",
      "kind": "css-pretty",
      "icon": "fa-solid fa-css3-alt",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "css format"
    },
    {
      "id": "css-minifier",
      "name": "CSS Minifier",
      "category": "Developer Tools",
      "description": "Minify CSS.",
      "kind": "css-min",
      "icon": "fa-solid fa-minimize",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "css minify"
    },
    {
      "id": "js-minifier",
      "name": "JavaScript Minifier",
      "category": "Developer Tools",
      "description": "Minify JavaScript by collapsing whitespace.",
      "kind": "js-min",
      "icon": "fa-brands fa-js",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "js minify"
    },
    {
      "id": "markdown-preview",
      "name": "Markdown Previewer",
      "category": "Developer Tools",
      "description": "Preview Markdown as HTML.",
      "kind": "md-preview",
      "icon": "fa-brands fa-markdown",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "markdown preview"
    },
    {
      "id": "regex-tester",
      "name": "Regex Tester",
      "category": "Developer Tools",
      "description": "Test a regular expression against text.",
      "kind": "regex",
      "icon": "fa-solid fa-magnifying-glass",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "regex test"
    },
    {
      "id": "base64-encoder",
      "name": "Base64 Encoder",
      "category": "Developer Tools",
      "description": "Encode text to Base64.",
      "kind": "b64-enc",
      "icon": "fa-solid fa-lock",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "base64"
    },
    {
      "id": "base64-decoder",
      "name": "Base64 Decoder",
      "category": "Developer Tools",
      "description": "Decode Base64 to text.",
      "kind": "b64-dec",
      "icon": "fa-solid fa-unlock",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "base64"
    },
    {
      "id": "jwt-decoder",
      "name": "JWT Decoder",
      "category": "Developer Tools",
      "description": "Decode a JWT header and payload (no verify).",
      "kind": "jwt-dec",
      "icon": "fa-solid fa-key",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "jwt token decode"
    },
    {
      "id": "uuid-generator",
      "name": "UUID Generator",
      "category": "Developer Tools",
      "description": "Generate UUID v4 values.",
      "kind": "uuid",
      "icon": "fa-solid fa-fingerprint",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "uuid guid"
    },
    {
      "id": "uuid-validator",
      "name": "UUID Validator",
      "category": "Developer Tools",
      "description": "Check if a string is a valid UUID.",
      "kind": "uuid-val",
      "icon": "fa-solid fa-check-double",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "uuid valid"
    },
    {
      "id": "unix-timestamp",
      "name": "Unix Timestamp Converter",
      "category": "Developer Tools",
      "description": "Convert Unix time to date and back.",
      "kind": "unix",
      "icon": "fa-solid fa-clock",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "unix epoch timestamp"
    },
    {
      "id": "hex-to-rgb",
      "name": "HEX to RGB",
      "category": "Developer Tools",
      "description": "Convert HEX color to RGB.",
      "kind": "color-conv",
      "icon": "fa-solid fa-droplet",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "hex rgb"
    },
    {
      "id": "rgb-to-hex",
      "name": "RGB to HEX",
      "category": "Developer Tools",
      "description": "Convert RGB color to HEX.",
      "kind": "color-conv",
      "icon": "fa-solid fa-droplet",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "rgb hex"
    },
    {
      "id": "css-gradient-generator",
      "name": "CSS Gradient Generator",
      "category": "Developer Tools",
      "description": "Build a CSS linear gradient.",
      "kind": "css-grad",
      "icon": "fa-solid fa-fill-drip",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "gradient css"
    },
    {
      "id": "css-box-shadow",
      "name": "CSS Box Shadow Generator",
      "category": "Developer Tools",
      "description": "Generate box-shadow CSS.",
      "kind": "css-shadow",
      "icon": "fa-solid fa-square",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "shadow"
    },
    {
      "id": "css-border-radius",
      "name": "CSS Border Radius Generator",
      "category": "Developer Tools",
      "description": "Generate border-radius CSS.",
      "kind": "css-radius",
      "icon": "fa-solid fa-square",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "radius"
    },
    {
      "id": "url-parser",
      "name": "URL Parser",
      "category": "Developer Tools",
      "description": "Parse protocol, host, path, and query.",
      "kind": "url-parse",
      "icon": "fa-solid fa-link",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "url parse"
    },
    {
      "id": "user-agent-parser",
      "name": "User Agent Parser",
      "category": "Developer Tools",
      "description": "Parse the current browser user agent.",
      "kind": "ua-parse",
      "icon": "fa-solid fa-globe",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "useragent"
    },
    {
      "id": "http-status",
      "name": "HTTP Status Code Checker",
      "category": "Developer Tools",
      "description": "Look up HTTP status code meaning.",
      "kind": "http-status",
      "icon": "fa-solid fa-server",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "http status"
    },
    {
      "id": "cron-parser",
      "name": "Cron Expression Parser",
      "category": "Developer Tools",
      "description": "Explain a 5-field cron expression.",
      "kind": "cron",
      "icon": "fa-solid fa-clock",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "cron"
    },
    {
      "id": "html-escape",
      "name": "HTML Escape",
      "category": "Developer Tools",
      "description": "Escape HTML special characters.",
      "kind": "html-enc",
      "icon": "fa-solid fa-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "escape"
    },
    {
      "id": "query-string-builder",
      "name": "Query String Builder",
      "category": "Developer Tools",
      "description": "Build a URL query string from pairs.",
      "kind": "qs-build",
      "icon": "fa-solid fa-list",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "querystring"
    },
    {
      "id": "json-to-csv",
      "name": "JSON to CSV",
      "category": "Developer Tools",
      "description": "Convert a JSON array to CSV.",
      "kind": "json-csv",
      "icon": "fa-solid fa-table",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "json csv"
    },
    {
      "id": "csv-to-json",
      "name": "CSV to JSON",
      "category": "Developer Tools",
      "description": "Convert CSV text to JSON.",
      "kind": "csv-json",
      "icon": "fa-solid fa-table",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "csv json"
    },
    {
      "id": "xml-to-json",
      "name": "XML to JSON",
      "category": "Developer Tools",
      "description": "Convert simple XML to JSON.",
      "kind": "xml-json",
      "icon": "fa-solid fa-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "xml json"
    },
    {
      "id": "hash-sha256",
      "name": "SHA-256 Generator",
      "category": "Developer Tools",
      "description": "Create a SHA-256 hash of text.",
      "kind": "hash",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sha256 hash"
    },
    {
      "id": "hash-sha512",
      "name": "SHA-512 Generator",
      "category": "Developer Tools",
      "description": "Create a SHA-512 hash of text.",
      "kind": "hash",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sha512"
    },
    {
      "id": "hash-md5-note",
      "name": "Checksum Helper",
      "category": "Developer Tools",
      "description": "Create SHA-256 checksum (preferred over MD5).",
      "kind": "hash",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "checksum"
    },
    {
      "id": "color-converter",
      "name": "Color Converter",
      "category": "Developer Tools",
      "description": "Convert between HEX, RGB, and HSL.",
      "kind": "color-conv",
      "icon": "fa-solid fa-palette",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "color convert"
    },
    {
      "id": "jwt-generator",
      "name": "JWT Builder (Unsigned)",
      "category": "Developer Tools",
      "description": "Build an unsigned JWT-like token for testing only.",
      "kind": "jwt-gen",
      "icon": "fa-solid fa-key",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "jwt test"
    },
    {
      "id": "password-generator",
      "name": "Password Generator",
      "category": "Security & Generator",
      "description": "Generate strong random passwords.",
      "kind": "password",
      "icon": "fa-solid fa-key",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "password random secure"
    },
    {
      "id": "username-generator",
      "name": "Username Generator",
      "category": "Security & Generator",
      "description": "Generate username ideas.",
      "kind": "username",
      "icon": "fa-solid fa-user",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "username"
    },
    {
      "id": "random-string",
      "name": "Random String Generator",
      "category": "Security & Generator",
      "description": "Generate a random alphanumeric string.",
      "kind": "rand-str",
      "icon": "fa-solid fa-shuffle",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "random string"
    },
    {
      "id": "token-generator",
      "name": "Token Generator",
      "category": "Security & Generator",
      "description": "Generate a random token.",
      "kind": "rand-str",
      "icon": "fa-solid fa-ticket",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "token"
    },
    {
      "id": "pin-generator",
      "name": "PIN Generator",
      "category": "Security & Generator",
      "description": "Generate numeric PINs.",
      "kind": "pin",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "pin"
    },
    {
      "id": "hex-generator",
      "name": "Hex Generator",
      "category": "Security & Generator",
      "description": "Generate random hexadecimal strings.",
      "kind": "hex-gen",
      "icon": "fa-solid fa-0",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "hex"
    },
    {
      "id": "secret-key-generator",
      "name": "Secret Key Generator",
      "category": "Security & Generator",
      "description": "Generate a long secret key for apps.",
      "kind": "rand-str",
      "icon": "fa-solid fa-shield-halved",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "secret key"
    },
    {
      "id": "color-generator",
      "name": "Random Color Generator",
      "category": "Security & Generator",
      "description": "Generate random HEX colors.",
      "kind": "rand-color",
      "icon": "fa-solid fa-palette",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "random color"
    },
    {
      "id": "hash-generator",
      "name": "Hash Generator",
      "category": "Security & Generator",
      "description": "Hash text with SHA-256 or SHA-512.",
      "kind": "hash",
      "icon": "fa-solid fa-fingerprint",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "hash sha"
    },
    {
      "id": "basic-calculator",
      "name": "Basic Calculator",
      "category": "Calculator",
      "description": "Add, subtract, multiply, and divide.",
      "kind": "calc-basic",
      "icon": "fa-solid fa-calculator",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "math calculate"
    },
    {
      "id": "scientific-calculator",
      "name": "Scientific Calculator",
      "category": "Calculator",
      "description": "sin, cos, tan, log, pow, sqrt.",
      "kind": "calc-sci",
      "icon": "fa-solid fa-square-root-variable",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "scientific sin cos"
    },
    {
      "id": "percentage-calculator",
      "name": "Percentage Calculator",
      "category": "Calculator",
      "description": "Find percentages, increase, and decrease.",
      "kind": "calc-pct",
      "icon": "fa-solid fa-percent",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "percent"
    },
    {
      "id": "discount-calculator",
      "name": "Discount Calculator",
      "category": "Calculator",
      "description": "Calculate sale price after discount.",
      "kind": "calc-discount",
      "icon": "fa-solid fa-tags",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "discount sale"
    },
    {
      "id": "profit-calculator",
      "name": "Profit Calculator",
      "category": "Calculator",
      "description": "Calculate profit and profit margin.",
      "kind": "calc-profit",
      "icon": "fa-solid fa-chart-line",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "profit margin"
    },
    {
      "id": "loss-calculator",
      "name": "Loss Calculator",
      "category": "Calculator",
      "description": "Calculate loss amount and percentage.",
      "kind": "calc-loss",
      "icon": "fa-solid fa-chart-line",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "loss"
    },
    {
      "id": "tax-calculator",
      "name": "Tax Calculator",
      "category": "Calculator",
      "description": "Add or remove tax from a price.",
      "kind": "calc-tax",
      "icon": "fa-solid fa-receipt",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "tax vat"
    },
    {
      "id": "tip-calculator",
      "name": "Tip Calculator",
      "category": "Calculator",
      "description": "Split a bill and calculate tip.",
      "kind": "calc-tip",
      "icon": "fa-solid fa-utensils",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "tip bill"
    },
    {
      "id": "age-calculator",
      "name": "Age Calculator",
      "category": "Calculator",
      "description": "Calculate age from a birth date.",
      "kind": "calc-age",
      "icon": "fa-solid fa-cake-candles",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "age birthday"
    },
    {
      "id": "date-difference",
      "name": "Date Difference Calculator",
      "category": "Calculator",
      "description": "Days between two dates.",
      "kind": "calc-datediff",
      "icon": "fa-solid fa-calendar",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "date difference days"
    },
    {
      "id": "bmi-calculator",
      "name": "BMI Calculator",
      "category": "Calculator",
      "description": "Calculate Body Mass Index.",
      "kind": "calc-bmi",
      "icon": "fa-solid fa-weight-scale",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "bmi health"
    },
    {
      "id": "bmr-calculator",
      "name": "BMR Calculator",
      "category": "Calculator",
      "description": "Estimate basal metabolic rate.",
      "kind": "calc-bmr",
      "icon": "fa-solid fa-heart-pulse",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "bmr calories"
    },
    {
      "id": "length-converter",
      "name": "Length Converter",
      "category": "Calculator",
      "description": "Convert meters, feet, inches, km, miles.",
      "kind": "unit-length",
      "icon": "fa-solid fa-ruler",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "meter feet inch"
    },
    {
      "id": "weight-converter",
      "name": "Weight Converter",
      "category": "Calculator",
      "description": "Convert kg, lb, oz, g.",
      "kind": "unit-weight",
      "icon": "fa-solid fa-weight-hanging",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "kg lb"
    },
    {
      "id": "temperature-converter",
      "name": "Temperature Converter",
      "category": "Calculator",
      "description": "Convert C, F, and Kelvin.",
      "kind": "unit-temp",
      "icon": "fa-solid fa-temperature-half",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "celsius fahrenheit"
    },
    {
      "id": "area-converter",
      "name": "Area Converter",
      "category": "Calculator",
      "description": "Convert m2, ft2, acres, hectares.",
      "kind": "unit-area",
      "icon": "fa-solid fa-vector-square",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "area m2"
    },
    {
      "id": "volume-converter",
      "name": "Volume Converter",
      "category": "Calculator",
      "description": "Convert liters, gallons, ml.",
      "kind": "unit-volume",
      "icon": "fa-solid fa-cube",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "liter gallon"
    },
    {
      "id": "speed-converter",
      "name": "Speed Converter",
      "category": "Calculator",
      "description": "Convert km/h, mph, m/s.",
      "kind": "unit-speed",
      "icon": "fa-solid fa-gauge-high",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "speed kmh mph"
    },
    {
      "id": "data-storage-converter",
      "name": "Data Storage Converter",
      "category": "Calculator",
      "description": "Convert B, KB, MB, GB, TB.",
      "kind": "unit-data",
      "icon": "fa-solid fa-hard-drive",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "mb gb tb"
    },
    {
      "id": "time-converter",
      "name": "Time Converter",
      "category": "Calculator",
      "description": "Convert seconds, minutes, hours, days.",
      "kind": "unit-time",
      "icon": "fa-solid fa-hourglass",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "time seconds"
    },
    {
      "id": "invoice-generator",
      "name": "Invoice Generator",
      "category": "Business Tools",
      "description": "Create a simple printable invoice.",
      "kind": "invoice",
      "icon": "fa-solid fa-file-invoice",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "invoice bill"
    },
    {
      "id": "receipt-generator",
      "name": "Receipt Generator",
      "category": "Business Tools",
      "description": "Create a simple receipt.",
      "kind": "receipt",
      "icon": "fa-solid fa-receipt",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "receipt"
    },
    {
      "id": "quotation-generator",
      "name": "Quotation Generator",
      "category": "Business Tools",
      "description": "Create a quotation document.",
      "kind": "quote",
      "icon": "fa-solid fa-file-invoice-dollar",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "quote quotation"
    },
    {
      "id": "margin-calculator",
      "name": "Margin Calculator",
      "category": "Business Tools",
      "description": "Calculate margin from cost and price.",
      "kind": "calc-margin",
      "icon": "fa-solid fa-percent",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "margin"
    },
    {
      "id": "markup-calculator",
      "name": "Markup Calculator",
      "category": "Business Tools",
      "description": "Calculate markup from cost and price.",
      "kind": "calc-markup",
      "icon": "fa-solid fa-percent",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "markup"
    },
    {
      "id": "sku-generator",
      "name": "SKU Generator",
      "category": "Business Tools",
      "description": "Generate product SKU codes.",
      "kind": "sku",
      "icon": "fa-solid fa-barcode",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sku product"
    },
    {
      "id": "invoice-number",
      "name": "Invoice Number Generator",
      "category": "Business Tools",
      "description": "Generate sequential-style invoice numbers.",
      "kind": "inv-no",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "invoice number"
    },
    {
      "id": "barcode-generator",
      "name": "Barcode Generator",
      "category": "Business Tools",
      "description": "Generate a Code128-style barcode SVG.",
      "kind": "barcode",
      "icon": "fa-solid fa-barcode",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "barcode"
    },
    {
      "id": "price-list-generator",
      "name": "Price List Generator",
      "category": "Business Tools",
      "description": "Build a simple price list table.",
      "kind": "pricelist",
      "icon": "fa-solid fa-list",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "price list"
    },
    {
      "id": "sales-calculator",
      "name": "Sales Calculator",
      "category": "Business Tools",
      "description": "Calculate total sales from units and price.",
      "kind": "calc-sales",
      "icon": "fa-solid fa-cash-register",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sales"
    },
    {
      "id": "color-palette",
      "name": "Color Palette Generator",
      "category": "Design Tools",
      "description": "Generate a 5-color palette.",
      "kind": "palette",
      "icon": "fa-solid fa-swatchbook",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "palette colors"
    },
    {
      "id": "gradient-generator",
      "name": "Gradient Generator",
      "category": "Design Tools",
      "description": "Create a CSS gradient and preview it.",
      "kind": "css-grad",
      "icon": "fa-solid fa-fill-drip",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "gradient"
    },
    {
      "id": "contrast-checker",
      "name": "Contrast Checker",
      "category": "Design Tools",
      "description": "Check WCAG contrast between two colors.",
      "kind": "contrast",
      "icon": "fa-solid fa-circle-half-stroke",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "contrast wcag"
    },
    {
      "id": "random-color",
      "name": "Random Color",
      "category": "Design Tools",
      "description": "Pick a random color with HEX and RGB.",
      "kind": "rand-color",
      "icon": "fa-solid fa-dice",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "random hex"
    },
    {
      "id": "social-image-size",
      "name": "Social Media Image Size Helper",
      "category": "Design Tools",
      "description": "Common social image sizes.",
      "kind": "social-sizes",
      "icon": "fa-solid fa-image",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "instagram youtube size"
    },
    {
      "id": "banner-size",
      "name": "Banner Size Calculator",
      "category": "Design Tools",
      "description": "Common ad and banner sizes.",
      "kind": "banner-sizes",
      "icon": "fa-solid fa-rectangle-ad",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "banner ads"
    },
    {
      "id": "font-pairing",
      "name": "Font Pairing Helper",
      "category": "Design Tools",
      "description": "Suggested font pairings for headings and body.",
      "kind": "font-pair",
      "icon": "fa-solid fa-font",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "font pair"
    },
    {
      "id": "logo-size-helper",
      "name": "Logo Size Helper",
      "category": "Design Tools",
      "description": "Common logo export sizes.",
      "kind": "logo-sizes",
      "icon": "fa-solid fa-vector-square",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "logo size"
    },
    {
      "id": "qr-generator",
      "name": "QR Code Generator",
      "category": "QR & Barcode",
      "description": "Generate a QR code from text or a URL.",
      "kind": "qr",
      "icon": "fa-solid fa-qrcode",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "qr code"
    },
    {
      "id": "wifi-qr",
      "name": "WiFi QR Generator",
      "category": "QR & Barcode",
      "description": "Create a WiFi login QR code.",
      "kind": "qr-wifi",
      "icon": "fa-solid fa-wifi",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "wifi qr"
    },
    {
      "id": "url-qr",
      "name": "URL QR Generator",
      "category": "QR & Barcode",
      "description": "Create a QR code for a URL.",
      "kind": "qr",
      "icon": "fa-solid fa-link",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "url qr"
    },
    {
      "id": "text-qr",
      "name": "Text QR Generator",
      "category": "QR & Barcode",
      "description": "Create a QR code for plain text.",
      "kind": "qr",
      "icon": "fa-solid fa-font",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "text qr"
    },
    {
      "id": "email-qr",
      "name": "Email QR Generator",
      "category": "QR & Barcode",
      "description": "Create a mailto QR code.",
      "kind": "qr-email",
      "icon": "fa-solid fa-envelope",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "email qr"
    },
    {
      "id": "phone-qr",
      "name": "Phone QR Generator",
      "category": "QR & Barcode",
      "description": "Create a tel: QR code.",
      "kind": "qr-phone",
      "icon": "fa-solid fa-phone",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "phone qr"
    },
    {
      "id": "sms-qr",
      "name": "SMS QR Generator",
      "category": "QR & Barcode",
      "description": "Create an SMS QR code.",
      "kind": "qr-sms",
      "icon": "fa-solid fa-comment-sms",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "sms qr"
    },
    {
      "id": "location-qr",
      "name": "Location QR Generator",
      "category": "QR & Barcode",
      "description": "Create a geo QR code.",
      "kind": "qr-geo",
      "icon": "fa-solid fa-location-dot",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "map location qr"
    },
    {
      "id": "caption-counter",
      "name": "Caption Counter",
      "category": "Social Media Tools",
      "description": "Count characters for captions.",
      "kind": "text-stats",
      "icon": "fa-solid fa-comment",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "caption instagram"
    },
    {
      "id": "hashtag-counter",
      "name": "Hashtag Counter",
      "category": "Social Media Tools",
      "description": "Count hashtags in text.",
      "kind": "hashtag-count",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "hashtag"
    },
    {
      "id": "bio-counter",
      "name": "Bio Character Counter",
      "category": "Social Media Tools",
      "description": "Count characters for a profile bio.",
      "kind": "text-stats",
      "icon": "fa-solid fa-user",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "bio twitter instagram"
    },
    {
      "id": "hashtag-maker",
      "name": "Hashtag Maker",
      "category": "Social Media Tools",
      "description": "Turn words into #hashtags.",
      "kind": "hashtag-make",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "hashtag generate"
    },
    {
      "id": "link-formatter",
      "name": "Link Formatter",
      "category": "Social Media Tools",
      "description": "Normalize and clean links.",
      "kind": "url-clean",
      "icon": "fa-solid fa-link",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "link url"
    },
    {
      "id": "username-ideas",
      "name": "Social Username Ideas",
      "category": "Social Media Tools",
      "description": "Generate handle ideas.",
      "kind": "username",
      "icon": "fa-solid fa-at",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "username handle"
    },
    {
      "id": "countdown",
      "name": "Countdown",
      "category": "Date & Time",
      "description": "Countdown to a target date.",
      "kind": "countdown",
      "icon": "fa-solid fa-hourglass-end",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "countdown"
    },
    {
      "id": "stopwatch",
      "name": "Stopwatch",
      "category": "Date & Time",
      "description": "Simple stopwatch.",
      "kind": "stopwatch",
      "icon": "fa-solid fa-stopwatch",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "stopwatch"
    },
    {
      "id": "timer",
      "name": "Timer",
      "category": "Date & Time",
      "description": "Countdown timer in minutes and seconds.",
      "kind": "timer",
      "icon": "fa-solid fa-clock",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "timer"
    },
    {
      "id": "world-clock",
      "name": "World Clock",
      "category": "Date & Time",
      "description": "Show current time in major timezones.",
      "kind": "worldclock",
      "icon": "fa-solid fa-earth-asia",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "timezone clock"
    },
    {
      "id": "date-formatter",
      "name": "Date Formatter",
      "category": "Date & Time",
      "description": "Format a date in common patterns.",
      "kind": "date-fmt",
      "icon": "fa-solid fa-calendar-days",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "date format"
    },
    {
      "id": "week-number",
      "name": "Week Number",
      "category": "Date & Time",
      "description": "Get ISO week number of a date.",
      "kind": "weeknum",
      "icon": "fa-solid fa-calendar-week",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "week iso"
    },
    {
      "id": "leap-year",
      "name": "Leap Year Checker",
      "category": "Date & Time",
      "description": "Check if a year is a leap year.",
      "kind": "leap",
      "icon": "fa-solid fa-calendar-check",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "leap year"
    },
    {
      "id": "working-days",
      "name": "Working Days Calculator",
      "category": "Date & Time",
      "description": "Count weekdays between two dates.",
      "kind": "workdays",
      "icon": "fa-solid fa-briefcase",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "working days weekday"
    },
    {
      "id": "timezone-converter",
      "name": "Timezone Converter",
      "category": "Date & Time",
      "description": "Convert a time between timezones.",
      "kind": "tz",
      "icon": "fa-solid fa-globe",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "timezone"
    },
    {
      "id": "txt-formatter",
      "name": "TXT Formatter",
      "category": "Document Tools",
      "description": "Normalize a text document.",
      "kind": "text-clean",
      "icon": "fa-solid fa-file-lines",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "txt"
    },
    {
      "id": "markdown-to-html",
      "name": "Markdown to HTML",
      "category": "Document Tools",
      "description": "Convert Markdown to HTML.",
      "kind": "md-html",
      "icon": "fa-brands fa-markdown",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "markdown html"
    },
    {
      "id": "html-to-text",
      "name": "HTML to Text",
      "category": "Document Tools",
      "description": "Strip tags from HTML.",
      "kind": "html-text",
      "icon": "fa-solid fa-file",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "html text"
    },
    {
      "id": "csv-viewer",
      "name": "CSV Viewer",
      "category": "Document Tools",
      "description": "Preview CSV as a table.",
      "kind": "csv-view",
      "icon": "fa-solid fa-table",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "csv table"
    },
    {
      "id": "csv-formatter",
      "name": "CSV Formatter",
      "category": "Document Tools",
      "description": "Pretty-print CSV rows.",
      "kind": "csv-fmt",
      "icon": "fa-solid fa-table",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "csv"
    },
    {
      "id": "file-size-checker",
      "name": "File Size Checker",
      "category": "File Tools",
      "description": "Check any file size and type.",
      "kind": "file-info",
      "icon": "fa-solid fa-file",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "filesize"
    },
    {
      "id": "file-extension",
      "name": "File Extension Checker",
      "category": "File Tools",
      "description": "Read a file name and extension.",
      "kind": "file-info",
      "icon": "fa-solid fa-file-circle-question",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "extension"
    },
    {
      "id": "mime-checker",
      "name": "MIME Type Checker",
      "category": "File Tools",
      "description": "Guess MIME type from a file.",
      "kind": "file-info",
      "icon": "fa-solid fa-file-code",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "mime"
    },
    {
      "id": "file-name-generator",
      "name": "File Name Generator",
      "category": "File Tools",
      "description": "Generate clean file names.",
      "kind": "filename",
      "icon": "fa-solid fa-file-signature",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "filename"
    },
    {
      "id": "file-hash",
      "name": "File Hash Calculator",
      "category": "File Tools",
      "description": "SHA-256 hash of a local file.",
      "kind": "file-hash",
      "icon": "fa-solid fa-fingerprint",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "hash checksum file"
    },
    {
      "id": "base64-file-encoder",
      "name": "Base64 File Encoder",
      "category": "File Tools",
      "description": "Encode a file to Base64.",
      "kind": "file-b64",
      "icon": "fa-solid fa-file-export",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "base64 file"
    },
    {
      "id": "gpa-calculator",
      "name": "GPA Calculator",
      "category": "Education",
      "description": "Calculate GPA from grade points.",
      "kind": "gpa",
      "icon": "fa-solid fa-graduation-cap",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "gpa grade"
    },
    {
      "id": "grade-calculator",
      "name": "Grade Calculator",
      "category": "Education",
      "description": "Find required score to hit a target grade.",
      "kind": "grade",
      "icon": "fa-solid fa-percent",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "grade exam"
    },
    {
      "id": "fraction-calculator",
      "name": "Fraction Calculator",
      "category": "Education",
      "description": "Add and simplify two fractions.",
      "kind": "fraction",
      "icon": "fa-solid fa-divide",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "fraction"
    },
    {
      "id": "multiplication-table",
      "name": "Multiplication Table",
      "category": "Education",
      "description": "Generate a multiplication table.",
      "kind": "multable",
      "icon": "fa-solid fa-table",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "multiply table"
    },
    {
      "id": "study-timer",
      "name": "Study Timer",
      "category": "Education",
      "description": "Simple study countdown timer.",
      "kind": "timer",
      "icon": "fa-solid fa-book",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "study timer"
    },
    {
      "id": "pomodoro-timer",
      "name": "Pomodoro Timer",
      "category": "Education",
      "description": "25/5 Pomodoro focus timer.",
      "kind": "pomodoro",
      "icon": "fa-solid fa-clock",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "pomodoro focus"
    },
    {
      "id": "todo-list",
      "name": "To-Do List",
      "category": "Productivity",
      "description": "Local to-do list saved in your browser.",
      "kind": "todo",
      "icon": "fa-solid fa-list-check",
      "popular": true,
      "newest": false,
      "premium": false,
      "keywords": "todo task"
    },
    {
      "id": "notes",
      "name": "Notes",
      "category": "Productivity",
      "description": "Quick notes saved locally.",
      "kind": "notes",
      "icon": "fa-solid fa-note-sticky",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "notes"
    },
    {
      "id": "checklist",
      "name": "Checklist",
      "category": "Productivity",
      "description": "Simple checklist.",
      "kind": "todo",
      "icon": "fa-solid fa-square-check",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "checklist"
    },
    {
      "id": "habit-tracker",
      "name": "Habit Tracker",
      "category": "Productivity",
      "description": "Track daily habits for this week.",
      "kind": "habits",
      "icon": "fa-solid fa-calendar-check",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "habit"
    },
    {
      "id": "random-picker",
      "name": "Random Picker",
      "category": "Productivity",
      "description": "Pick a random item from a list.",
      "kind": "picker",
      "icon": "fa-solid fa-dice",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "random pick"
    },
    {
      "id": "random-number",
      "name": "Random Number Generator",
      "category": "Productivity",
      "description": "Generate a random number in a range.",
      "kind": "rand-num",
      "icon": "fa-solid fa-dice-five",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "random number"
    },
    {
      "id": "decision-maker",
      "name": "Decision Maker",
      "category": "Productivity",
      "description": "Yes / No / Maybe helper.",
      "kind": "decision",
      "icon": "fa-solid fa-circle-question",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "decision yes no"
    },
    {
      "id": "simple-expense",
      "name": "Simple Expense Tracker",
      "category": "Productivity",
      "description": "Add expenses and see a total.",
      "kind": "expense",
      "icon": "fa-solid fa-wallet",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "expense money"
    },
    {
      "id": "clipboard-note",
      "name": "Quick Clipboard Note",
      "category": "Utility",
      "description": "Type text and copy it instantly.",
      "kind": "clipnote",
      "icon": "fa-solid fa-clipboard",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "clipboard"
    },
    {
      "id": "case-converter-all",
      "name": "All Case Converter",
      "category": "Utility",
      "description": "Convert text to many case styles at once.",
      "kind": "case-all",
      "icon": "fa-solid fa-font",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "case"
    },
    {
      "id": "list-numberer",
      "name": "List Numberer",
      "category": "Utility",
      "description": "Turn lines into a numbered list.",
      "kind": "line-num",
      "icon": "fa-solid fa-ol",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "list number"
    },
    {
      "id": "whitespace-visualizer",
      "name": "Whitespace Visualizer",
      "category": "Utility",
      "description": "Show spaces and tabs in text.",
      "kind": "ws-vis",
      "icon": "fa-solid fa-eye",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "whitespace"
    },
    {
      "id": "ai-summarizer",
      "name": "AI Summarizer",
      "category": "AI Tools",
      "description": "Summarize long text. Requires an AI API key on the server.",
      "kind": "ai",
      "icon": "fa-solid fa-align-left",
      "popular": true,
      "newest": true,
      "premium": true,
      "keywords": "ai summarize"
    },
    {
      "id": "ai-rewriter",
      "name": "AI Rewriter",
      "category": "AI Tools",
      "description": "Rewrite text more clearly. Requires server AI API.",
      "kind": "ai",
      "icon": "fa-solid fa-pen",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai rewrite"
    },
    {
      "id": "ai-translator",
      "name": "AI Translator",
      "category": "AI Tools",
      "description": "Translate text. Requires server AI API.",
      "kind": "ai",
      "icon": "fa-solid fa-language",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai translate"
    },
    {
      "id": "ai-caption",
      "name": "AI Caption Generator",
      "category": "AI Tools",
      "description": "Generate captions from a topic.",
      "kind": "ai",
      "icon": "fa-solid fa-comment",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai caption"
    },
    {
      "id": "ai-product",
      "name": "AI Product Description",
      "category": "AI Tools",
      "description": "Write a product description.",
      "kind": "ai",
      "icon": "fa-solid fa-box",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai product"
    },
    {
      "id": "ai-title",
      "name": "AI Title Generator",
      "category": "AI Tools",
      "description": "Generate title ideas.",
      "kind": "ai",
      "icon": "fa-solid fa-heading",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai title"
    },
    {
      "id": "ai-hashtag",
      "name": "AI Hashtag Generator",
      "category": "AI Tools",
      "description": "Suggest hashtags from a topic.",
      "kind": "ai",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai hashtag"
    },
    {
      "id": "ai-helper",
      "name": "AI Text Helper",
      "category": "AI Tools",
      "description": "General text helper.",
      "kind": "ai",
      "icon": "fa-solid fa-robot",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai helper"
    },
    {
      "id": "ai-ideas",
      "name": "AI Idea Generator",
      "category": "AI Tools",
      "description": "Brainstorm ideas from a topic.",
      "kind": "ai",
      "icon": "fa-solid fa-lightbulb",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai ideas"
    },
    {
      "id": "ai-email",
      "name": "AI Email Writer",
      "category": "AI Tools",
      "description": "Draft a polite email.",
      "kind": "ai",
      "icon": "fa-solid fa-envelope",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai email"
    },
    {
      "id": "ai-study",
      "name": "AI Study Helper",
      "category": "AI Tools",
      "description": "Explain a topic in simple language.",
      "kind": "ai",
      "icon": "fa-solid fa-book-open",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai study"
    },
    {
      "id": "ai-qa",
      "name": "AI Q&A",
      "category": "AI Tools",
      "description": "Ask a question and get an answer.",
      "kind": "ai",
      "icon": "fa-solid fa-circle-question",
      "popular": false,
      "newest": true,
      "premium": true,
      "keywords": "ai question"
    },
    {
      "id": "image-mirror-text",
      "name": "Image Label Maker",
      "category": "Image Tools",
      "description": "Put a short label on the bottom of an image.",
      "kind": "image-watermark",
      "icon": "fa-solid fa-tag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "label"
    },
    {
      "id": "png-transparent-check",
      "name": "Image Type Checker",
      "category": "Image Tools",
      "description": "See if a file is PNG, JPG, or WEBP.",
      "kind": "image-info",
      "icon": "fa-solid fa-circle-info",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "type"
    },
    {
      "id": "text-wrap",
      "name": "Text Wrapper",
      "category": "Text Tools",
      "description": "Wrap text to a given line width.",
      "kind": "text-wrap",
      "icon": "fa-solid fa-align-justify",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "wrap"
    },
    {
      "id": "remove-punctuation",
      "name": "Remove Punctuation",
      "category": "Text Tools",
      "description": "Strip punctuation from text.",
      "kind": "no-punct",
      "icon": "fa-solid fa-i-cursor",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "punctuation"
    },
    {
      "id": "initials-generator",
      "name": "Initials Generator",
      "category": "Text Tools",
      "description": "Create initials from a name.",
      "kind": "initials",
      "icon": "fa-solid fa-signature",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "initials"
    },
    {
      "id": "slug-to-title",
      "name": "Slug to Title",
      "category": "Text Tools",
      "description": "Turn a slug into a readable title.",
      "kind": "slug-title",
      "icon": "fa-solid fa-heading",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "slug"
    },
    {
      "id": "json-keys",
      "name": "JSON Key Lister",
      "category": "Developer Tools",
      "description": "List top-level keys in a JSON object.",
      "kind": "json-keys",
      "icon": "fa-solid fa-key",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "json keys"
    },
    {
      "id": "css-unit-converter",
      "name": "CSS Unit Helper",
      "category": "Developer Tools",
      "description": "Convert px and rem at 16px base.",
      "kind": "css-unit",
      "icon": "fa-solid fa-ruler",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "px rem"
    },
    {
      "id": "rgb-to-hsl",
      "name": "RGB to HSL",
      "category": "Developer Tools",
      "description": "Convert RGB to HSL.",
      "kind": "color-conv",
      "icon": "fa-solid fa-droplet",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "hsl"
    },
    {
      "id": "number-base",
      "name": "Number Base Converter",
      "category": "Developer Tools",
      "description": "Convert between decimal, binary, hex.",
      "kind": "num-base",
      "icon": "fa-solid fa-hashtag",
      "popular": false,
      "newest": false,
      "premium": false,
      "keywords": "binary hex decimal"
    }
      ,
    {"id":"quote-maker","name":"Quote Maker","category":"Design Tools","description":"Buat gambar quote kuning-hitam.","kind":"quote-img","icon":"fa-solid fa-quote-left","popular":true,"newest":true,"premium":false,"keywords":"quote caption"},
    {"id":"brat-text","name":"Brat Text","category":"Design Tools","description":"Tulisan besar style poster.","kind":"brat","icon":"fa-solid fa-font","popular":true,"newest":true,"premium":false,"keywords":"brat poster text"},
    {"id":"nokia-sms","name":"Nokia Message","category":"Design Tools","description":"Tampilan SMS HP jadul.","kind":"nokia","icon":"fa-solid fa-mobile-screen","popular":true,"newest":true,"premium":false,"keywords":"nokia sms retro"},
    {"id":"text-to-speech","name":"Text to Speech","category":"Text Tools","description":"Bacakan teks di browser.","kind":"tts","icon":"fa-solid fa-volume-high","popular":true,"newest":true,"premium":false,"keywords":"tts suara"},
    {"id":"dice-roller","name":"Dice Roller","category":"Utility","description":"Lempar dadu 1–6.","kind":"dice","icon":"fa-solid fa-dice","popular":true,"newest":true,"premium":false,"keywords":"dadu random"},
    {"id":"coin-flip","name":"Coin Flip","category":"Utility","description":"Lempar koin.","kind":"coin","icon":"fa-solid fa-coins","popular":true,"newest":true,"premium":false,"keywords":"koin"},
    {"id":"random-pick","name":"Random Picker","category":"Utility","description":"Pilih acak dari daftar.","kind":"pick","icon":"fa-solid fa-shuffle","popular":false,"newest":true,"premium":false,"keywords":"acak undian"},
    {"id":"daily-assistant","name":"Asisten Harian","category":"AI Tools","description":"Tanya jam, hitung, caption, resep.","kind":"ai","icon":"fa-solid fa-comments","popular":true,"newest":true,"premium":false,"keywords":"ai tanya harian"},
    {"id":"ig-caption","name":"Caption Maker","category":"Social Media Tools","description":"Ide caption singkat.","kind":"ai","icon":"fa-brands fa-instagram","popular":true,"newest":true,"premium":false,"keywords":"caption ig"},
    {"id":"wa-status","name":"Status WA Maker","category":"Social Media Tools","description":"Ide status WhatsApp.","kind":"ai","icon":"fa-brands fa-whatsapp","popular":true,"newest":true,"premium":false,"keywords":"status wa"},
    {"id":"color-poster","name":"Color Poster","category":"Design Tools","description":"Poster warna dari teks.","kind":"poster-color","icon":"fa-solid fa-palette","popular":false,"newest":true,"premium":false,"keywords":"poster"},
    {"id":"checklist-maker","name":"Checklist Maker","category":"Productivity","description":"Buat daftar centang.","kind":"checklist","icon":"fa-solid fa-list-check","popular":false,"newest":true,"premium":false,"keywords":"todo checklist"},
    {"id":"world-clock","name":"World Clock","category":"Date & Time","description":"Jam beberapa kota.","kind":"world-clock","icon":"fa-solid fa-earth-asia","popular":false,"newest":true,"premium":false,"keywords":"jam dunia wib"},
    {"id":"percent-calc","name":"Percent Calculator","category":"Calculator","description":"Hitung persen dan diskon.","kind":"percent","icon":"fa-solid fa-percent","popular":true,"newest":true,"premium":false,"keywords":"diskon persen"},
    {"id":"ip-lookup","name":"IP Lookup","category":"Developer Tools","description":"Cek negara dari IP publik.","kind":"ip-lookup","icon":"fa-solid fa-network-wired","popular":false,"newest":true,"premium":false,"keywords":"ip negara"}
  ]
};
