/* NAILONG TOOLS registry — generated, do not edit by hand unless needed */
window.NT_REGISTRY = {
  "version": "148.027.00",
  "generated": true,
  "count": 265,
  "categories": [
    "Alat Gambar",
    "Alat PDF",
    "Alat Video",
    "Alat Audio",
    "Alat Teks",
    "Alat Pengembang",
    "Keamanan & Generator",
    "Kalkulator",
    "Alat Bisnis",
    "Alat Desain",
    "QR & Barcode",
    "Media Sosial",
    "Tanggal & Waktu",
    "Alat Dokumen",
    "Alat Berkas",
    "Edukasi",
    "Produktivitas",
    "Utilitas",
    "Alat AI",
    "Alat VIP"
],
  "tools": [
  {
    "id": "image-compressor",
    "name": "Image Compressor",
    "category": "Alat Gambar",
    "description": "Kompres gambar di browser.",
    "kind": "image-compress",
    "icon": "fa-solid fa-compress",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "compress optimize jpg png webp size"
  },
  {
    "id": "image-resizer",
    "name": "Image Resizer",
    "category": "Alat Gambar",
    "description": "Ubah ukuran gambar.",
    "kind": "image-resize",
    "icon": "fa-solid fa-up-right-and-down-left-from-center",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "resize scale width height"
  },
  {
    "id": "image-cropper",
    "name": "Image Cropper",
    "category": "Alat Gambar",
    "description": "Potong gambar.",
    "kind": "image-crop",
    "icon": "fa-solid fa-crop",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "crop cut"
  },
  {
    "id": "image-rotator",
    "name": "Image Rotator",
    "category": "Alat Gambar",
    "description": "Putar gambar.",
    "kind": "image-rotate",
    "icon": "fa-solid fa-rotate",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "rotate turn"
  },
  {
    "id": "image-flipper",
    "name": "Image Flipper",
    "category": "Alat Gambar",
    "description": "Balik gambar.",
    "kind": "image-flip",
    "icon": "fa-solid fa-left-right",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "flip mirror"
  },
  {
    "id": "image-converter",
    "name": "Image Converter",
    "category": "Alat Gambar",
    "description": "Ubah format gambar.",
    "kind": "image-convert",
    "icon": "fa-solid fa-exchange-alt",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "convert format jpg png webp"
  },
  {
    "id": "jpg-to-png",
    "name": "JPG to PNG",
    "category": "Alat Gambar",
    "description": "Ubah format gambar.",
    "kind": "image-convert",
    "icon": "fa-solid fa-file-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "jpg jpeg png"
  },
  {
    "id": "png-to-jpg",
    "name": "PNG to JPG",
    "category": "Alat Gambar",
    "description": "Ubah format gambar.",
    "kind": "image-convert",
    "icon": "fa-solid fa-file-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "png jpg"
  },
  {
    "id": "jpg-to-webp",
    "name": "JPG to WEBP",
    "category": "Alat Gambar",
    "description": "Ubah format gambar.",
    "kind": "image-convert",
    "icon": "fa-solid fa-file-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "jpg webp"
  },
  {
    "id": "png-to-webp",
    "name": "PNG to WEBP",
    "category": "Alat Gambar",
    "description": "Ubah format gambar.",
    "kind": "image-convert",
    "icon": "fa-solid fa-file-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "png webp"
  },
  {
    "id": "webp-to-jpg",
    "name": "WEBP to JPG",
    "category": "Alat Gambar",
    "description": "Ubah format gambar.",
    "kind": "image-convert",
    "icon": "fa-solid fa-file-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "webp jpg"
  },
  {
    "id": "webp-to-png",
    "name": "WEBP to PNG",
    "category": "Alat Gambar",
    "description": "Ubah format gambar.",
    "kind": "image-convert",
    "icon": "fa-solid fa-file-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "webp png"
  },
  {
    "id": "image-to-base64",
    "name": "Image to Base64",
    "category": "Alat Gambar",
    "description": "Ubah gambar ke Base64.",
    "kind": "image-base64",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "base64 encode"
  },
  {
    "id": "base64-to-image",
    "name": "Base64 to Image",
    "category": "Alat Gambar",
    "description": "Ubah gambar menjadi Base64.",
    "kind": "base64-image",
    "icon": "fa-solid fa-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "base64 decode"
  },
  {
    "id": "image-blur",
    "name": "Image Blur",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-droplet",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "blur filter"
  },
  {
    "id": "image-grayscale",
    "name": "Image Grayscale",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-circle-half-stroke",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "gray black white"
  },
  {
    "id": "image-brightness",
    "name": "Image Brightness",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-sun",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "bright dark"
  },
  {
    "id": "image-contrast",
    "name": "Image Contrast",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-circle-adjust",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "contrast"
  },
  {
    "id": "image-saturation",
    "name": "Image Saturation",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-palette",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "saturate color"
  },
  {
    "id": "image-sepia",
    "name": "Image Sepia",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-camera-retro",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sepia vintage"
  },
  {
    "id": "image-invert",
    "name": "Image Invert",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-circle-half-stroke",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "invert negative"
  },
  {
    "id": "image-watermark",
    "name": "Image Watermark",
    "category": "Alat Gambar",
    "description": "Tambah tanda air pada gambar.",
    "kind": "image-watermark",
    "icon": "fa-solid fa-stamp",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "watermark text"
  },
  {
    "id": "image-text-overlay",
    "name": "Image Text Overlay",
    "category": "Alat Gambar",
    "description": "Tambah tanda air pada gambar.",
    "kind": "image-watermark",
    "icon": "fa-solid fa-font",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "text overlay caption"
  },
  {
    "id": "image-dimension-checker",
    "name": "Image Dimension Checker",
    "category": "Alat Gambar",
    "description": "Lihat info gambar.",
    "kind": "image-info",
    "icon": "fa-solid fa-ruler-combined",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "size dimension width height"
  },
  {
    "id": "image-file-size-checker",
    "name": "Image File Size Checker",
    "category": "Alat Gambar",
    "description": "Lihat info gambar.",
    "kind": "image-info",
    "icon": "fa-solid fa-weight-scale",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "filesize kb mb"
  },
  {
    "id": "image-color-picker",
    "name": "Image Color Picker",
    "category": "Alat Gambar",
    "description": "Pilih warna dari gambar.",
    "kind": "image-picker",
    "icon": "fa-solid fa-eye-dropper",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "color pick hex"
  },
  {
    "id": "image-border",
    "name": "Image Border Generator",
    "category": "Alat Gambar",
    "description": "Tambah pinggiran gambar.",
    "kind": "image-border",
    "icon": "fa-solid fa-border-all",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "border frame"
  },
  {
    "id": "image-bg-color",
    "name": "Image Background Color",
    "category": "Alat Gambar",
    "description": "Tambah latar pada gambar.",
    "kind": "image-bg",
    "icon": "fa-solid fa-fill-drip",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "background color"
  },
  {
    "id": "favicon-generator",
    "name": "Favicon Generator",
    "category": "Alat Gambar",
    "description": "Buat ikon kecil dari gambar.",
    "kind": "image-favicon",
    "icon": "fa-solid fa-star",
    "popular": false,
    "newest": true,
    "premium": false,
    "keywords": "favicon ico"
  },
  {
    "id": "image-aspect-ratio",
    "name": "Image Aspect Ratio Calculator",
    "category": "Alat Gambar",
    "description": "Hitung rasio aspek gambar atau video.",
    "kind": "calc-aspect",
    "icon": "fa-solid fa-crop-simple",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "aspect ratio 16:9"
  },
  {
    "id": "image-pixelate",
    "name": "Image Pixelate",
    "category": "Alat Gambar",
    "description": "Buat gambar berpiksel.",
    "kind": "image-pixelate",
    "icon": "fa-solid fa-table-cells",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "pixel mosaic"
  },
  {
    "id": "image-rounded",
    "name": "Image Rounded Corners",
    "category": "Alat Gambar",
    "description": "Buat sudut gambar membulat.",
    "kind": "image-round",
    "icon": "fa-solid fa-square",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "round corner"
  },
  {
    "id": "image-opacity",
    "name": "Image Opacity",
    "category": "Alat Gambar",
    "description": "Terapkan filter gambar.",
    "kind": "image-filter",
    "icon": "fa-solid fa-droplet",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "opacity transparent"
  },
  {
    "id": "screenshot-cropper",
    "name": "Screenshot Cropper",
    "category": "Alat Gambar",
    "description": "Potong gambar.",
    "kind": "image-crop",
    "icon": "fa-solid fa-scissors",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "screenshot crop"
  },
  {
    "id": "pdf-merge",
    "name": "PDF Merger",
    "category": "Alat PDF",
    "description": "Gabung beberapa PDF.",
    "kind": "pdf-merge",
    "icon": "fa-solid fa-object-group",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "merge combine pdf"
  },
  {
    "id": "pdf-split",
    "name": "PDF Split",
    "category": "Alat PDF",
    "description": "Pisah PDF.",
    "kind": "pdf-split",
    "icon": "fa-solid fa-scissors",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "split pages"
  },
  {
    "id": "pdf-rotate",
    "name": "PDF Rotate",
    "category": "Alat PDF",
    "description": "Putar halaman PDF.",
    "kind": "pdf-rotate",
    "icon": "fa-solid fa-rotate",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "rotate pdf"
  },
  {
    "id": "images-to-pdf",
    "name": "Images to PDF",
    "category": "Alat PDF",
    "description": "Gabung gambar menjadi PDF.",
    "kind": "images-pdf",
    "icon": "fa-solid fa-file-pdf",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "image pdf jpg png"
  },
  {
    "id": "pdf-info",
    "name": "PDF Information",
    "category": "Alat PDF",
    "description": "Lihat info PDF.",
    "kind": "pdf-info",
    "icon": "fa-solid fa-circle-info",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "info metadata pages"
  },
  {
    "id": "text-to-pdf",
    "name": "Text to PDF",
    "category": "Alat PDF",
    "description": "Ubah teks menjadi PDF.",
    "kind": "text-pdf",
    "icon": "fa-solid fa-file-lines",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "text pdf"
  },
  {
    "id": "pdf-page-extract",
    "name": "PDF Extract Pages",
    "category": "Alat PDF",
    "description": "Ambil teks dari PDF.",
    "kind": "pdf-extract",
    "icon": "fa-solid fa-file-export",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "extract pages"
  },
  {
    "id": "pdf-size-checker",
    "name": "PDF Size Checker",
    "category": "Alat PDF",
    "description": "Lihat info PDF.",
    "kind": "pdf-info",
    "icon": "fa-solid fa-weight-hanging",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "size pdf"
  },
  {
    "id": "video-info",
    "name": "Video Information",
    "category": "Alat Video",
    "description": "Info berkas media.",
    "kind": "media-info",
    "icon": "fa-solid fa-circle-info",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "video info metadata"
  },
  {
    "id": "video-thumbnail",
    "name": "Video Thumbnail Generator",
    "category": "Alat Video",
    "description": "Ambil gambar dari video.",
    "kind": "video-thumb",
    "icon": "fa-solid fa-image",
    "popular": false,
    "newest": true,
    "premium": false,
    "keywords": "thumbnail frame capture"
  },
  {
    "id": "video-aspect-ratio",
    "name": "Video Aspect Ratio Calculator",
    "category": "Alat Video",
    "description": "Hitung rasio aspek gambar atau video.",
    "kind": "calc-aspect",
    "icon": "fa-solid fa-film",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "16:9 9:16"
  },
  {
    "id": "gif-info",
    "name": "GIF Information",
    "category": "Alat Video",
    "description": "Lihat info berkas.",
    "kind": "file-info",
    "icon": "fa-solid fa-gift",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "gif info"
  },
  {
    "id": "audio-info",
    "name": "Audio File Information",
    "category": "Alat Audio",
    "description": "Info berkas media.",
    "kind": "media-info",
    "icon": "fa-solid fa-music",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "audio info"
  },
  {
    "id": "audio-volume-preview",
    "name": "Audio Volume Preview",
    "category": "Alat Audio",
    "description": "Pratinjau berkas audio di browser.",
    "kind": "audio-preview",
    "icon": "fa-solid fa-volume-high",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "volume preview"
  },
  {
    "id": "word-counter",
    "name": "Word Counter",
    "category": "Alat Teks",
    "description": "Hitung kata dan karakter.",
    "kind": "text-stats",
    "icon": "fa-solid fa-calculator",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "word count character"
  },
  {
    "id": "character-counter",
    "name": "Character Counter",
    "category": "Alat Teks",
    "description": "Hitung kata dan karakter.",
    "kind": "text-stats",
    "icon": "fa-solid fa-font",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "character length"
  },
  {
    "id": "sentence-counter",
    "name": "Sentence Counter",
    "category": "Alat Teks",
    "description": "Hitung kata dan karakter.",
    "kind": "text-stats",
    "icon": "fa-solid fa-align-left",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sentence"
  },
  {
    "id": "paragraph-counter",
    "name": "Paragraph Counter",
    "category": "Alat Teks",
    "description": "Hitung kata dan karakter.",
    "kind": "text-stats",
    "icon": "fa-solid fa-paragraph",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "paragraph"
  },
  {
    "id": "text-cleaner",
    "name": "Text Cleaner",
    "category": "Alat Teks",
    "description": "Bersihkan teks.",
    "kind": "text-clean",
    "icon": "fa-solid fa-broom",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "clean space"
  },
  {
    "id": "remove-duplicate-lines",
    "name": "Remove Duplicate Lines",
    "category": "Alat Teks",
    "description": "Ambil baris unik.",
    "kind": "text-unique",
    "icon": "fa-solid fa-clone",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "duplicate unique"
  },
  {
    "id": "sort-lines",
    "name": "Sort Lines",
    "category": "Alat Teks",
    "description": "Urutkan baris teks.",
    "kind": "text-sort",
    "icon": "fa-solid fa-arrow-down-a-z",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sort alphabet"
  },
  {
    "id": "reverse-text",
    "name": "Reverse Text",
    "category": "Alat Teks",
    "description": "Balik teks.",
    "kind": "text-reverse",
    "icon": "fa-solid fa-left-right",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "reverse"
  },
  {
    "id": "uppercase-converter",
    "name": "Uppercase Converter",
    "category": "Alat Teks",
    "description": "Ubah huruf teks.",
    "kind": "text-case",
    "icon": "fa-solid fa-a",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "upper caps"
  },
  {
    "id": "lowercase-converter",
    "name": "Lowercase Converter",
    "category": "Alat Teks",
    "description": "Ubah huruf teks.",
    "kind": "text-case",
    "icon": "fa-solid fa-a",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "lower"
  },
  {
    "id": "title-case",
    "name": "Title Case",
    "category": "Alat Teks",
    "description": "Ubah huruf teks.",
    "kind": "text-case",
    "icon": "fa-solid fa-heading",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "title case"
  },
  {
    "id": "sentence-case",
    "name": "Sentence Case",
    "category": "Alat Teks",
    "description": "Ubah huruf teks.",
    "kind": "text-case",
    "icon": "fa-solid fa-align-left",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sentence case"
  },
  {
    "id": "remove-spaces",
    "name": "Remove Spaces",
    "category": "Alat Teks",
    "description": "Hapus spasi.",
    "kind": "text-nospaces",
    "icon": "fa-solid fa-minus",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "space remove"
  },
  {
    "id": "remove-empty-lines",
    "name": "Remove Empty Lines",
    "category": "Alat Teks",
    "description": "Hapus baris kosong.",
    "kind": "text-noempty",
    "icon": "fa-solid fa-grip-lines",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "empty lines"
  },
  {
    "id": "text-diff",
    "name": "Text Compare",
    "category": "Alat Teks",
    "description": "Bandingkan dua teks.",
    "kind": "text-diff",
    "icon": "fa-solid fa-code-compare",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "diff compare"
  },
  {
    "id": "text-to-slug",
    "name": "Text to Slug",
    "category": "Alat Teks",
    "description": "Buat slug dari teks.",
    "kind": "text-slug",
    "icon": "fa-solid fa-link",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "slug url"
  },
  {
    "id": "lorem-ipsum",
    "name": "Lorem Ipsum Generator",
    "category": "Alat Teks",
    "description": "Buat teks contoh.",
    "kind": "lorem",
    "icon": "fa-solid fa-align-justify",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "lorem ipsum dummy"
  },
  {
    "id": "random-text",
    "name": "Random Text Generator",
    "category": "Alat Teks",
    "description": "Paragraf acak.",
    "kind": "rand-text",
    "icon": "fa-solid fa-shuffle",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "random words"
  },
  {
    "id": "morse-encoder",
    "name": "Morse Code Encoder",
    "category": "Alat Teks",
    "description": "Ubah teks menjadi kode Morse.",
    "kind": "morse-enc",
    "icon": "fa-solid fa-ellipsis",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "morse"
  },
  {
    "id": "morse-decoder",
    "name": "Morse Code Decoder",
    "category": "Alat Teks",
    "description": "Ubah kode Morse menjadi teks.",
    "kind": "morse-dec",
    "icon": "fa-solid fa-ellipsis",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "morse decode"
  },
  {
    "id": "text-to-binary",
    "name": "Text to Binary",
    "category": "Alat Teks",
    "description": "Ubah teks menjadi biner.",
    "kind": "bin-enc",
    "icon": "fa-solid fa-1",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "binary"
  },
  {
    "id": "binary-to-text",
    "name": "Binary to Text",
    "category": "Alat Teks",
    "description": "Ubah teks biner menjadi teks biasa.",
    "kind": "bin-dec",
    "icon": "fa-solid fa-0",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "binary decode"
  },
  {
    "id": "rot13",
    "name": "ROT13",
    "category": "Alat Teks",
    "description": "Sandi ROT13.",
    "kind": "rot13",
    "icon": "fa-solid fa-rotate",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "rot13 cipher"
  },
  {
    "id": "url-encoder",
    "name": "URL Encoder",
    "category": "Alat Teks",
    "description": "Encode tautan.",
    "kind": "url-enc",
    "icon": "fa-solid fa-percent",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "encode url"
  },
  {
    "id": "url-decoder",
    "name": "URL Decoder",
    "category": "Alat Teks",
    "description": "Decode tautan.",
    "kind": "url-dec",
    "icon": "fa-solid fa-percent",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "decode url"
  },
  {
    "id": "html-entity-encoder",
    "name": "HTML Entity Encoder",
    "category": "Alat Teks",
    "description": "Encode teks ke HTML.",
    "kind": "html-enc",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "html entity"
  },
  {
    "id": "html-entity-decoder",
    "name": "HTML Entity Decoder",
    "category": "Alat Teks",
    "description": "Decode entitas HTML.",
    "kind": "html-dec",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "html entity"
  },
  {
    "id": "line-counter",
    "name": "Line Counter",
    "category": "Alat Teks",
    "description": "Hitung kata dan karakter.",
    "kind": "text-stats",
    "icon": "fa-solid fa-list-ol",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "lines"
  },
  {
    "id": "repeat-text",
    "name": "Repeat Text",
    "category": "Alat Teks",
    "description": "Ulangi teks.",
    "kind": "text-repeat",
    "icon": "fa-solid fa-copy",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "repeat"
  },
  {
    "id": "extract-emails",
    "name": "Email Extractor",
    "category": "Alat Teks",
    "description": "Ambil alamat email dari teks.",
    "kind": "extract-email",
    "icon": "fa-solid fa-envelope",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "email extract"
  },
  {
    "id": "extract-urls",
    "name": "URL Extractor",
    "category": "Alat Teks",
    "description": "Ambil tautan dari teks.",
    "kind": "extract-url",
    "icon": "fa-solid fa-link",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "url extract"
  },
  {
    "id": "word-frequency",
    "name": "Word Frequency",
    "category": "Alat Teks",
    "description": "Hitung kata yang sering muncul.",
    "kind": "word-freq",
    "icon": "fa-solid fa-chart-simple",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "frequency"
  },
  {
    "id": "add-line-numbers",
    "name": "Add Line Numbers",
    "category": "Alat Teks",
    "description": "Beri nomor baris pada teks.",
    "kind": "line-num",
    "icon": "fa-solid fa-list-ol",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "line number"
  },
  {
    "id": "trim-lines",
    "name": "Trim Lines",
    "category": "Alat Teks",
    "description": "Rapikan spasi tiap baris.",
    "kind": "trim-lines",
    "icon": "fa-solid fa-scissors",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "trim"
  },
  {
    "id": "camel-case",
    "name": "Camel Case Converter",
    "category": "Alat Teks",
    "description": "Ubah huruf teks.",
    "kind": "text-case",
    "icon": "fa-solid fa-i-cursor",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "camelCase"
  },
  {
    "id": "snake-case",
    "name": "Snake Case Converter",
    "category": "Alat Teks",
    "description": "Ubah huruf teks.",
    "kind": "text-case",
    "icon": "fa-solid fa-i-cursor",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "snake_case"
  },
  {
    "id": "kebab-case",
    "name": "Kebab Case Converter",
    "category": "Alat Teks",
    "description": "Ubah huruf teks.",
    "kind": "text-case",
    "icon": "fa-solid fa-i-cursor",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "kebab-case"
  },
  {
    "id": "json-formatter",
    "name": "JSON Formatter",
    "category": "Alat Pengembang",
    "description": "Rapikan JSON.",
    "kind": "json-pretty",
    "icon": "fa-solid fa-brackets-curly",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "json format pretty"
  },
  {
    "id": "json-validator",
    "name": "JSON Validator",
    "category": "Alat Pengembang",
    "description": "Rapikan JSON.",
    "kind": "json-pretty",
    "icon": "fa-solid fa-check",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "json validate"
  },
  {
    "id": "json-minifier",
    "name": "JSON Minifier",
    "category": "Alat Pengembang",
    "description": "Perkecil JSON.",
    "kind": "json-min",
    "icon": "fa-solid fa-minimize",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "json minify"
  },
  {
    "id": "xml-formatter",
    "name": "XML Formatter",
    "category": "Alat Pengembang",
    "description": "Rapikan XML.",
    "kind": "xml-pretty",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "xml format"
  },
  {
    "id": "html-formatter",
    "name": "HTML Formatter",
    "category": "Alat Pengembang",
    "description": "Rapikan HTML.",
    "kind": "html-pretty",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "html format"
  },
  {
    "id": "html-minifier",
    "name": "HTML Minifier",
    "category": "Alat Pengembang",
    "description": "Perkecil HTML.",
    "kind": "html-min",
    "icon": "fa-solid fa-minimize",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "html minify"
  },
  {
    "id": "css-formatter",
    "name": "CSS Formatter",
    "category": "Alat Pengembang",
    "description": "Rapikan kode CSS.",
    "kind": "css-pretty",
    "icon": "fa-solid fa-css3-alt",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "css format"
  },
  {
    "id": "css-minifier",
    "name": "CSS Minifier",
    "category": "Alat Pengembang",
    "description": "Perkecil kode CSS.",
    "kind": "css-min",
    "icon": "fa-solid fa-minimize",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "css minify"
  },
  {
    "id": "js-minifier",
    "name": "JavaScript Minifier",
    "category": "Alat Pengembang",
    "description": "Perkecil kode JavaScript.",
    "kind": "js-min",
    "icon": "fa-brands fa-js",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "js minify"
  },
  {
    "id": "markdown-preview",
    "name": "Markdown Previewer",
    "category": "Alat Pengembang",
    "description": "Lihat hasil Markdown.",
    "kind": "md-preview",
    "icon": "fa-brands fa-markdown",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "markdown preview"
  },
  {
    "id": "regex-tester",
    "name": "Regex Tester",
    "category": "Alat Pengembang",
    "description": "Uji pola regex.",
    "kind": "regex",
    "icon": "fa-solid fa-magnifying-glass",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "regex test"
  },
  {
    "id": "base64-encoder",
    "name": "Base64 Encoder",
    "category": "Alat Pengembang",
    "description": "Ubah teks menjadi Base64.",
    "kind": "b64-enc",
    "icon": "fa-solid fa-lock",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "base64"
  },
  {
    "id": "base64-decoder",
    "name": "Base64 Decoder",
    "category": "Alat Pengembang",
    "description": "Ubah Base64 menjadi teks.",
    "kind": "b64-dec",
    "icon": "fa-solid fa-unlock",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "base64"
  },
  {
    "id": "jwt-decoder",
    "name": "JWT Decoder",
    "category": "Alat Pengembang",
    "description": "Baca isi token JWT.",
    "kind": "jwt-dec",
    "icon": "fa-solid fa-key",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "jwt token decode"
  },
  {
    "id": "uuid-generator",
    "name": "UUID Generator",
    "category": "Alat Pengembang",
    "description": "Buat UUID.",
    "kind": "uuid",
    "icon": "fa-solid fa-fingerprint",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "uuid guid"
  },
  {
    "id": "uuid-validator",
    "name": "UUID Validator",
    "category": "Alat Pengembang",
    "description": "Cek UUID valid.",
    "kind": "uuid-val",
    "icon": "fa-solid fa-check-double",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "uuid valid"
  },
  {
    "id": "unix-timestamp",
    "name": "Unix Timestamp Converter",
    "category": "Alat Pengembang",
    "description": "Ubah waktu Unix.",
    "kind": "unix",
    "icon": "fa-solid fa-clock",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "unix epoch timestamp"
  },
  {
    "id": "hex-to-rgb",
    "name": "HEX to RGB",
    "category": "Alat Pengembang",
    "description": "Ubah format warna.",
    "kind": "color-conv",
    "icon": "fa-solid fa-droplet",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "hex rgb"
  },
  {
    "id": "rgb-to-hex",
    "name": "RGB to HEX",
    "category": "Alat Pengembang",
    "description": "Ubah format warna.",
    "kind": "color-conv",
    "icon": "fa-solid fa-droplet",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "rgb hex"
  },
  {
    "id": "css-gradient-generator",
    "name": "CSS Gradient Generator",
    "category": "Alat Pengembang",
    "description": "Buat gradasi CSS.",
    "kind": "css-grad",
    "icon": "fa-solid fa-fill-drip",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "gradient css"
  },
  {
    "id": "css-box-shadow",
    "name": "CSS Box Shadow Generator",
    "category": "Alat Pengembang",
    "description": "Buat bayangan CSS.",
    "kind": "css-shadow",
    "icon": "fa-solid fa-square",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "shadow"
  },
  {
    "id": "css-border-radius",
    "name": "CSS Border Radius Generator",
    "category": "Alat Pengembang",
    "description": "Buat sudut membulat CSS.",
    "kind": "css-radius",
    "icon": "fa-solid fa-square",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "radius"
  },
  {
    "id": "url-parser",
    "name": "URL Parser",
    "category": "Alat Pengembang",
    "description": "Urai bagian tautan.",
    "kind": "url-parse",
    "icon": "fa-solid fa-link",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "url parse"
  },
  {
    "id": "user-agent-parser",
    "name": "User Agent Parser",
    "category": "Alat Pengembang",
    "description": "Baca user agent.",
    "kind": "ua-parse",
    "icon": "fa-solid fa-globe",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "useragent"
  },
  {
    "id": "http-status",
    "name": "HTTP Status Code Checker",
    "category": "Alat Pengembang",
    "description": "Arti kode status HTTP.",
    "kind": "http-status",
    "icon": "fa-solid fa-server",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "http status"
  },
  {
    "id": "cron-parser",
    "name": "Cron Expression Parser",
    "category": "Alat Pengembang",
    "description": "Baca atau buat jadwal cron.",
    "kind": "cron",
    "icon": "fa-solid fa-clock",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "cron"
  },
  {
    "id": "html-escape",
    "name": "HTML Escape",
    "category": "Alat Pengembang",
    "description": "Encode teks ke HTML.",
    "kind": "html-enc",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "escape"
  },
  {
    "id": "query-string-builder",
    "name": "Query String Builder",
    "category": "Alat Pengembang",
    "description": "Susun query URL.",
    "kind": "qs-build",
    "icon": "fa-solid fa-list",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "querystring"
  },
  {
    "id": "json-to-csv",
    "name": "JSON to CSV",
    "category": "Alat Pengembang",
    "description": "Ubah JSON menjadi CSV.",
    "kind": "json-csv",
    "icon": "fa-solid fa-table",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "json csv"
  },
  {
    "id": "csv-to-json",
    "name": "CSV to JSON",
    "category": "Alat Pengembang",
    "description": "Ubah CSV menjadi JSON.",
    "kind": "csv-json",
    "icon": "fa-solid fa-table",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "csv json"
  },
  {
    "id": "xml-to-json",
    "name": "XML to JSON",
    "category": "Alat Pengembang",
    "description": "Ubah XML menjadi JSON.",
    "kind": "xml-json",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "xml json"
  },
  {
    "id": "hash-sha256",
    "name": "SHA-256 Generator",
    "category": "Alat Pengembang",
    "description": "Buat hash teks.",
    "kind": "hash",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sha256 hash"
  },
  {
    "id": "hash-sha512",
    "name": "SHA-512 Generator",
    "category": "Alat Pengembang",
    "description": "Buat hash teks.",
    "kind": "hash",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sha512"
  },
  {
    "id": "hash-md5-note",
    "name": "Checksum Helper",
    "category": "Alat Pengembang",
    "description": "Buat hash teks.",
    "kind": "hash",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "checksum"
  },
  {
    "id": "color-converter",
    "name": "Color Converter",
    "category": "Alat Pengembang",
    "description": "Ubah format warna.",
    "kind": "color-conv",
    "icon": "fa-solid fa-palette",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "color convert"
  },
  {
    "id": "jwt-generator",
    "name": "JWT Builder (Unsigned)",
    "category": "Alat Pengembang",
    "description": "Buat token JWT sederhana.",
    "kind": "jwt-gen",
    "icon": "fa-solid fa-key",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "jwt test"
  },
  {
    "id": "password-generator",
    "name": "Password Generator",
    "category": "Keamanan & Generator",
    "description": "Buat kata sandi acak.",
    "kind": "password",
    "icon": "fa-solid fa-key",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "password random secure"
  },
  {
    "id": "username-generator",
    "name": "Username Generator",
    "category": "Keamanan & Generator",
    "description": "Saran nama pengguna.",
    "kind": "username",
    "icon": "fa-solid fa-user",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "username"
  },
  {
    "id": "random-string",
    "name": "Random String Generator",
    "category": "Keamanan & Generator",
    "description": "Teks acak.",
    "kind": "rand-str",
    "icon": "fa-solid fa-shuffle",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "random string"
  },
  {
    "id": "token-generator",
    "name": "Token Generator",
    "category": "Keamanan & Generator",
    "description": "Teks acak.",
    "kind": "rand-str",
    "icon": "fa-solid fa-ticket",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "token"
  },
  {
    "id": "pin-generator",
    "name": "PIN Generator",
    "category": "Keamanan & Generator",
    "description": "Buat PIN acak.",
    "kind": "pin",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "pin"
  },
  {
    "id": "hex-generator",
    "name": "Hex Generator",
    "category": "Keamanan & Generator",
    "description": "Buat kode hex acak.",
    "kind": "hex-gen",
    "icon": "fa-solid fa-0",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "hex"
  },
  {
    "id": "secret-key-generator",
    "name": "Secret Key Generator",
    "category": "Keamanan & Generator",
    "description": "Teks acak.",
    "kind": "rand-str",
    "icon": "fa-solid fa-shield-halved",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "secret key"
  },
  {
    "id": "color-generator",
    "name": "Random Color Generator",
    "category": "Keamanan & Generator",
    "description": "Warna acak.",
    "kind": "rand-color",
    "icon": "fa-solid fa-palette",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "random color"
  },
  {
    "id": "hash-generator",
    "name": "Hash Generator",
    "category": "Keamanan & Generator",
    "description": "Buat hash teks.",
    "kind": "hash",
    "icon": "fa-solid fa-fingerprint",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "hash sha"
  },
  {
    "id": "basic-calculator",
    "name": "Basic Calculator",
    "category": "Kalkulator",
    "description": "Kalkulator hitung biasa.",
    "kind": "calc-basic",
    "icon": "fa-solid fa-calculator",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "math calculate"
  },
  {
    "id": "scientific-calculator",
    "name": "Scientific Calculator",
    "category": "Kalkulator",
    "description": "Kalkulator ilmiah dasar.",
    "kind": "calc-sci",
    "icon": "fa-solid fa-square-root-variable",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "scientific sin cos"
  },
  {
    "id": "percentage-calculator",
    "name": "Percentage Calculator",
    "category": "Kalkulator",
    "description": "Hitung persentase.",
    "kind": "calc-pct",
    "icon": "fa-solid fa-percent",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "percent"
  },
  {
    "id": "discount-calculator",
    "name": "Discount Calculator",
    "category": "Kalkulator",
    "description": "Hitung harga setelah diskon.",
    "kind": "calc-discount",
    "icon": "fa-solid fa-tags",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "discount sale"
  },
  {
    "id": "profit-calculator",
    "name": "Profit Calculator",
    "category": "Kalkulator",
    "description": "Hitung laba.",
    "kind": "calc-profit",
    "icon": "fa-solid fa-chart-line",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "profit margin"
  },
  {
    "id": "loss-calculator",
    "name": "Loss Calculator",
    "category": "Kalkulator",
    "description": "Hitung rugi dari modal dan jual.",
    "kind": "calc-loss",
    "icon": "fa-solid fa-chart-line",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "loss"
  },
  {
    "id": "tax-calculator",
    "name": "Tax Calculator",
    "category": "Kalkulator",
    "description": "Hitung pajak dari nominal.",
    "kind": "calc-tax",
    "icon": "fa-solid fa-receipt",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "tax vat"
  },
  {
    "id": "tip-calculator",
    "name": "Tip Calculator",
    "category": "Kalkulator",
    "description": "Hitung tip.",
    "kind": "calc-tip",
    "icon": "fa-solid fa-utensils",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "tip bill"
  },
  {
    "id": "age-calculator",
    "name": "Age Calculator",
    "category": "Kalkulator",
    "description": "Hitung umur dari tanggal lahir.",
    "kind": "calc-age",
    "icon": "fa-solid fa-cake-candles",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "age birthday"
  },
  {
    "id": "date-difference",
    "name": "Date Difference Calculator",
    "category": "Kalkulator",
    "description": "Hitung selisih dua tanggal.",
    "kind": "calc-datediff",
    "icon": "fa-solid fa-calendar",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "date difference days"
  },
  {
    "id": "bmi-calculator",
    "name": "BMI Calculator",
    "category": "Kalkulator",
    "description": "Hitung IMT dari tinggi dan berat.",
    "kind": "calc-bmi",
    "icon": "fa-solid fa-weight-scale",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "bmi health"
  },
  {
    "id": "bmr-calculator",
    "name": "BMR Calculator",
    "category": "Kalkulator",
    "description": "Perkiraan kebutuhan kalori harian.",
    "kind": "calc-bmr",
    "icon": "fa-solid fa-heart-pulse",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "bmr calories"
  },
  {
    "id": "length-converter",
    "name": "Length Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan panjang.",
    "kind": "unit-length",
    "icon": "fa-solid fa-ruler",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "meter feet inch"
  },
  {
    "id": "weight-converter",
    "name": "Weight Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan berat.",
    "kind": "unit-weight",
    "icon": "fa-solid fa-weight-hanging",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "kg lb"
  },
  {
    "id": "temperature-converter",
    "name": "Temperature Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan suhu.",
    "kind": "unit-temp",
    "icon": "fa-solid fa-temperature-half",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "celsius fahrenheit"
  },
  {
    "id": "area-converter",
    "name": "Area Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan luas.",
    "kind": "unit-area",
    "icon": "fa-solid fa-vector-square",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "area m2"
  },
  {
    "id": "volume-converter",
    "name": "Volume Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan volume.",
    "kind": "unit-volume",
    "icon": "fa-solid fa-cube",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "liter gallon"
  },
  {
    "id": "speed-converter",
    "name": "Speed Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan kecepatan.",
    "kind": "unit-speed",
    "icon": "fa-solid fa-gauge-high",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "speed kmh mph"
  },
  {
    "id": "data-storage-converter",
    "name": "Data Storage Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan data.",
    "kind": "unit-data",
    "icon": "fa-solid fa-hard-drive",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "mb gb tb"
  },
  {
    "id": "time-converter",
    "name": "Time Converter",
    "category": "Kalkulator",
    "description": "Ubah satuan waktu.",
    "kind": "unit-time",
    "icon": "fa-solid fa-hourglass",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "time seconds"
  },
  {
    "id": "invoice-generator",
    "name": "Invoice Generator",
    "category": "Alat Bisnis",
    "description": "Buat invoice sederhana.",
    "kind": "invoice",
    "icon": "fa-solid fa-file-invoice",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "invoice bill"
  },
  {
    "id": "receipt-generator",
    "name": "Receipt Generator",
    "category": "Alat Bisnis",
    "description": "Buat struk sederhana.",
    "kind": "receipt",
    "icon": "fa-solid fa-receipt",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "receipt"
  },
  {
    "id": "quotation-generator",
    "name": "Quotation Generator",
    "category": "Alat Bisnis",
    "description": "Rapikan kutipan.",
    "kind": "quote",
    "icon": "fa-solid fa-file-invoice-dollar",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "quote quotation"
  },
  {
    "id": "margin-calculator",
    "name": "Margin Calculator",
    "category": "Alat Bisnis",
    "description": "Hitung margin keuntungan.",
    "kind": "calc-margin",
    "icon": "fa-solid fa-percent",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "margin"
  },
  {
    "id": "markup-calculator",
    "name": "Markup Calculator",
    "category": "Alat Bisnis",
    "description": "Hitung markup harga.",
    "kind": "calc-markup",
    "icon": "fa-solid fa-percent",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "markup"
  },
  {
    "id": "sku-generator",
    "name": "SKU Generator",
    "category": "Alat Bisnis",
    "description": "Buat kode SKU.",
    "kind": "sku",
    "icon": "fa-solid fa-barcode",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sku product"
  },
  {
    "id": "invoice-number",
    "name": "Invoice Number Generator",
    "category": "Alat Bisnis",
    "description": "Buat nomor invoice.",
    "kind": "inv-no",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "invoice number"
  },
  {
    "id": "barcode-generator",
    "name": "Barcode Generator",
    "category": "Alat Bisnis",
    "description": "Buat barcode dari teks.",
    "kind": "barcode",
    "icon": "fa-solid fa-barcode",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "barcode"
  },
  {
    "id": "price-list-generator",
    "name": "Price List Generator",
    "category": "Alat Bisnis",
    "description": "Buat daftar harga.",
    "kind": "pricelist",
    "icon": "fa-solid fa-list",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "price list"
  },
  {
    "id": "sales-calculator",
    "name": "Sales Calculator",
    "category": "Alat Bisnis",
    "description": "Hitung total penjualan.",
    "kind": "calc-sales",
    "icon": "fa-solid fa-cash-register",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sales"
  },
  {
    "id": "color-palette",
    "name": "Color Palette Generator",
    "category": "Alat Desain",
    "description": "Buat palet warna.",
    "kind": "palette",
    "icon": "fa-solid fa-swatchbook",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "palette colors"
  },
  {
    "id": "gradient-generator",
    "name": "Gradient Generator",
    "category": "Alat Desain",
    "description": "Buat gradasi CSS.",
    "kind": "css-grad",
    "icon": "fa-solid fa-fill-drip",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "gradient"
  },
  {
    "id": "contrast-checker",
    "name": "Contrast Checker",
    "category": "Alat Desain",
    "description": "Cek kontras warna teks dan latar.",
    "kind": "contrast",
    "icon": "fa-solid fa-circle-half-stroke",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "contrast wcag"
  },
  {
    "id": "random-color",
    "name": "Random Color",
    "category": "Alat Desain",
    "description": "Warna acak.",
    "kind": "rand-color",
    "icon": "fa-solid fa-dice",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "random hex"
  },
  {
    "id": "social-image-size",
    "name": "Social Media Image Size Helper",
    "category": "Alat Desain",
    "description": "Ukuran gambar media sosial.",
    "kind": "social-sizes",
    "icon": "fa-solid fa-image",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "instagram youtube size"
  },
  {
    "id": "banner-size",
    "name": "Banner Size Calculator",
    "category": "Alat Desain",
    "description": "Ukuran banner umum untuk desain.",
    "kind": "banner-sizes",
    "icon": "fa-solid fa-rectangle-ad",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "banner ads"
  },
  {
    "id": "font-pairing",
    "name": "Font Pairing Helper",
    "category": "Alat Desain",
    "description": "Saran pasangan font.",
    "kind": "font-pair",
    "icon": "fa-solid fa-font",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "font pair"
  },
  {
    "id": "logo-size-helper",
    "name": "Logo Size Helper",
    "category": "Alat Desain",
    "description": "Ukuran logo umum.",
    "kind": "logo-sizes",
    "icon": "fa-solid fa-vector-square",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "logo size"
  },
  {
    "id": "qr-generator",
    "name": "QR Code Generator",
    "category": "QR & Barcode",
    "description": "Buat kode QR dari teks atau tautan.",
    "kind": "qr",
    "icon": "fa-solid fa-qrcode",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "qr code"
  },
  {
    "id": "wifi-qr",
    "name": "WiFi QR Generator",
    "category": "QR & Barcode",
    "description": "QR untuk Wi-Fi.",
    "kind": "qr-wifi",
    "icon": "fa-solid fa-wifi",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "wifi qr"
  },
  {
    "id": "url-qr",
    "name": "URL QR Generator",
    "category": "QR & Barcode",
    "description": "Buat kode QR dari teks atau tautan.",
    "kind": "qr",
    "icon": "fa-solid fa-link",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "url qr"
  },
  {
    "id": "text-qr",
    "name": "Text QR Generator",
    "category": "QR & Barcode",
    "description": "Buat kode QR dari teks atau tautan.",
    "kind": "qr",
    "icon": "fa-solid fa-font",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "text qr"
  },
  {
    "id": "email-qr",
    "name": "Email QR Generator",
    "category": "QR & Barcode",
    "description": "QR untuk email.",
    "kind": "qr-email",
    "icon": "fa-solid fa-envelope",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "email qr"
  },
  {
    "id": "phone-qr",
    "name": "Phone QR Generator",
    "category": "QR & Barcode",
    "description": "QR untuk nomor telepon.",
    "kind": "qr-phone",
    "icon": "fa-solid fa-phone",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "phone qr"
  },
  {
    "id": "sms-qr",
    "name": "SMS QR Generator",
    "category": "QR & Barcode",
    "description": "QR untuk SMS.",
    "kind": "qr-sms",
    "icon": "fa-solid fa-comment-sms",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "sms qr"
  },
  {
    "id": "location-qr",
    "name": "Location QR Generator",
    "category": "QR & Barcode",
    "description": "QR untuk lokasi.",
    "kind": "qr-geo",
    "icon": "fa-solid fa-location-dot",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "map location qr"
  },
  {
    "id": "caption-counter",
    "name": "Caption Counter",
    "category": "Media Sosial",
    "description": "Hitung kata dan karakter.",
    "kind": "text-stats",
    "icon": "fa-solid fa-comment",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "caption instagram"
  },
  {
    "id": "hashtag-counter",
    "name": "Hashtag Counter",
    "category": "Media Sosial",
    "description": "Hitung hashtag.",
    "kind": "hashtag-count",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "hashtag"
  },
  {
    "id": "bio-counter",
    "name": "Bio Character Counter",
    "category": "Media Sosial",
    "description": "Hitung kata dan karakter.",
    "kind": "text-stats",
    "icon": "fa-solid fa-user",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "bio twitter instagram"
  },
  {
    "id": "hashtag-maker",
    "name": "Hashtag Maker",
    "category": "Media Sosial",
    "description": "Buat hashtag dari kata.",
    "kind": "hashtag-make",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "hashtag generate"
  },
  {
    "id": "link-formatter",
    "name": "Link Formatter",
    "category": "Media Sosial",
    "description": "Bersihkan tautan.",
    "kind": "url-clean",
    "icon": "fa-solid fa-link",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "link url"
  },
  {
    "id": "username-ideas",
    "name": "Social Username Ideas",
    "category": "Media Sosial",
    "description": "Saran nama pengguna.",
    "kind": "username",
    "icon": "fa-solid fa-at",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "username handle"
  },
  {
    "id": "countdown",
    "name": "Countdown",
    "category": "Tanggal & Waktu",
    "description": "Hitung mundur ke waktu tertentu.",
    "kind": "countdown",
    "icon": "fa-solid fa-hourglass-end",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "countdown"
  },
  {
    "id": "stopwatch",
    "name": "Stopwatch",
    "category": "Tanggal & Waktu",
    "description": "Stopwatch.",
    "kind": "stopwatch",
    "icon": "fa-solid fa-stopwatch",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "stopwatch"
  },
  {
    "id": "timer",
    "name": "Timer",
    "category": "Tanggal & Waktu",
    "description": "Atur penghitung waktu.",
    "kind": "timer",
    "icon": "fa-solid fa-clock",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "timer"
  },
  {
    "id": "world-clock",
    "name": "World Clock",
    "category": "Tanggal & Waktu",
    "description": "Jam beberapa kota.",
    "kind": "worldclock",
    "icon": "fa-solid fa-earth-asia",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "timezone clock"
  },
  {
    "id": "date-formatter",
    "name": "Date Formatter",
    "category": "Tanggal & Waktu",
    "description": "Ubah format tanggal.",
    "kind": "date-fmt",
    "icon": "fa-solid fa-calendar-days",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "date format"
  },
  {
    "id": "week-number",
    "name": "Week Number",
    "category": "Tanggal & Waktu",
    "description": "Nomor minggu dalam tahun.",
    "kind": "weeknum",
    "icon": "fa-solid fa-calendar-week",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "week iso"
  },
  {
    "id": "leap-year",
    "name": "Leap Year Checker",
    "category": "Tanggal & Waktu",
    "description": "Cek tahun kabisat.",
    "kind": "leap",
    "icon": "fa-solid fa-calendar-check",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "leap year"
  },
  {
    "id": "working-days",
    "name": "Working Days Calculator",
    "category": "Tanggal & Waktu",
    "description": "Hitung hari kerja.",
    "kind": "workdays",
    "icon": "fa-solid fa-briefcase",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "working days weekday"
  },
  {
    "id": "timezone-converter",
    "name": "Timezone Converter",
    "category": "Tanggal & Waktu",
    "description": "Lihat zona waktu.",
    "kind": "tz",
    "icon": "fa-solid fa-globe",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "timezone"
  },
  {
    "id": "txt-formatter",
    "name": "TXT Formatter",
    "category": "Alat Dokumen",
    "description": "Bersihkan teks.",
    "kind": "text-clean",
    "icon": "fa-solid fa-file-lines",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "txt"
  },
  {
    "id": "markdown-to-html",
    "name": "Markdown to HTML",
    "category": "Alat Dokumen",
    "description": "Ubah Markdown menjadi HTML.",
    "kind": "md-html",
    "icon": "fa-brands fa-markdown",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "markdown html"
  },
  {
    "id": "html-to-text",
    "name": "HTML to Text",
    "category": "Alat Dokumen",
    "description": "Ambil teks dari HTML.",
    "kind": "html-text",
    "icon": "fa-solid fa-file",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "html text"
  },
  {
    "id": "csv-viewer",
    "name": "CSV Viewer",
    "category": "Alat Dokumen",
    "description": "Lihat isi CSV.",
    "kind": "csv-view",
    "icon": "fa-solid fa-table",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "csv table"
  },
  {
    "id": "csv-formatter",
    "name": "CSV Formatter",
    "category": "Alat Dokumen",
    "description": "Rapikan berkas CSV.",
    "kind": "csv-fmt",
    "icon": "fa-solid fa-table",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "csv"
  },
  {
    "id": "file-size-checker",
    "name": "File Size Checker",
    "category": "Alat Berkas",
    "description": "Lihat info berkas.",
    "kind": "file-info",
    "icon": "fa-solid fa-file",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "filesize"
  },
  {
    "id": "file-extension",
    "name": "File Extension Checker",
    "category": "Alat Berkas",
    "description": "Lihat info berkas.",
    "kind": "file-info",
    "icon": "fa-solid fa-file-circle-question",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "extension"
  },
  {
    "id": "mime-checker",
    "name": "MIME Type Checker",
    "category": "Alat Berkas",
    "description": "Lihat info berkas.",
    "kind": "file-info",
    "icon": "fa-solid fa-file-code",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "mime"
  },
  {
    "id": "file-name-generator",
    "name": "File Name Generator",
    "category": "Alat Berkas",
    "description": "Rapikan nama berkas.",
    "kind": "filename",
    "icon": "fa-solid fa-file-signature",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "filename"
  },
  {
    "id": "file-hash",
    "name": "File Hash Calculator",
    "category": "Alat Berkas",
    "description": "Hitung hash berkas.",
    "kind": "file-hash",
    "icon": "fa-solid fa-fingerprint",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "hash checksum file"
  },
  {
    "id": "base64-file-encoder",
    "name": "Base64 File Encoder",
    "category": "Alat Berkas",
    "description": "Ubah berkas menjadi Base64.",
    "kind": "file-b64",
    "icon": "fa-solid fa-file-export",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "base64 file"
  },
  {
    "id": "gpa-calculator",
    "name": "GPA Calculator",
    "category": "Edukasi",
    "description": "Hitung nilai rata-rata.",
    "kind": "gpa",
    "icon": "fa-solid fa-graduation-cap",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "gpa grade"
  },
  {
    "id": "grade-calculator",
    "name": "Grade Calculator",
    "category": "Edukasi",
    "description": "Ubah nilai angka ke huruf.",
    "kind": "grade",
    "icon": "fa-solid fa-percent",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "grade exam"
  },
  {
    "id": "fraction-calculator",
    "name": "Fraction Calculator",
    "category": "Edukasi",
    "description": "Ubah desimal menjadi pecahan.",
    "kind": "fraction",
    "icon": "fa-solid fa-divide",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "fraction"
  },
  {
    "id": "multiplication-table",
    "name": "Multiplication Table",
    "category": "Edukasi",
    "description": "Tabel perkalian.",
    "kind": "multable",
    "icon": "fa-solid fa-table",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "multiply table"
  },
  {
    "id": "study-timer",
    "name": "Study Timer",
    "category": "Edukasi",
    "description": "Atur penghitung waktu.",
    "kind": "timer",
    "icon": "fa-solid fa-book",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "study timer"
  },
  {
    "id": "pomodoro-timer",
    "name": "Pomodoro Timer",
    "category": "Edukasi",
    "description": "Timer fokus Pomodoro.",
    "kind": "pomodoro",
    "icon": "fa-solid fa-clock",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "pomodoro focus"
  },
  {
    "id": "todo-list",
    "name": "To-Do List",
    "category": "Produktivitas",
    "description": "Daftar tugas.",
    "kind": "todo",
    "icon": "fa-solid fa-list-check",
    "popular": true,
    "newest": false,
    "premium": false,
    "keywords": "todo task"
  },
  {
    "id": "notes",
    "name": "Notes",
    "category": "Produktivitas",
    "description": "Catatan di perangkat.",
    "kind": "notes",
    "icon": "fa-solid fa-note-sticky",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "notes"
  },
  {
    "id": "checklist",
    "name": "Checklist",
    "category": "Produktivitas",
    "description": "Daftar tugas.",
    "kind": "todo",
    "icon": "fa-solid fa-square-check",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "checklist"
  },
  {
    "id": "habit-tracker",
    "name": "Habit Tracker",
    "category": "Produktivitas",
    "description": "Catat kebiasaan harian.",
    "kind": "habits",
    "icon": "fa-solid fa-calendar-check",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "habit"
  },
  {
    "id": "random-picker",
    "name": "Random Picker",
    "category": "Produktivitas",
    "description": "Pemilih warna.",
    "kind": "picker",
    "icon": "fa-solid fa-dice",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "random pick"
  },
  {
    "id": "random-number",
    "name": "Random Number Generator",
    "category": "Produktivitas",
    "description": "Angka acak.",
    "kind": "rand-num",
    "icon": "fa-solid fa-dice-five",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "random number"
  },
  {
    "id": "decision-maker",
    "name": "Decision Maker",
    "category": "Produktivitas",
    "description": "Bantu pilih ya atau tidak.",
    "kind": "decision",
    "icon": "fa-solid fa-circle-question",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "decision yes no"
  },
  {
    "id": "simple-expense",
    "name": "Simple Expense Tracker",
    "category": "Produktivitas",
    "description": "Catat pengeluaran.",
    "kind": "expense",
    "icon": "fa-solid fa-wallet",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "expense money"
  },
  {
    "id": "clipboard-note",
    "name": "Quick Clipboard Note",
    "category": "Utilitas",
    "description": "Catatan cepat di perangkat.",
    "kind": "clipnote",
    "icon": "fa-solid fa-clipboard",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "clipboard"
  },
  {
    "id": "case-converter-all",
    "name": "All Case Converter",
    "category": "Utilitas",
    "description": "Ubah huruf besar, kecil, atau judul.",
    "kind": "case-all",
    "icon": "fa-solid fa-font",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "case"
  },
  {
    "id": "list-numberer",
    "name": "List Numberer",
    "category": "Utilitas",
    "description": "Beri nomor baris pada teks.",
    "kind": "line-num",
    "icon": "fa-solid fa-ol",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "list number"
  },
  {
    "id": "whitespace-visualizer",
    "name": "Whitespace Visualizer",
    "category": "Utilitas",
    "description": "Tampilkan spasi tersembunyi.",
    "kind": "ws-vis",
    "icon": "fa-solid fa-eye",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "whitespace"
  },
  {
    "id": "ai-summarizer",
    "name": "AI Summarizer",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-align-left",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "ai summarize"
  },
  {
    "id": "ai-rewriter",
    "name": "AI Rewriter",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-pen",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai rewrite"
  },
  {
    "id": "ai-translator",
    "name": "AI Translator",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-language",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai translate"
  },
  {
    "id": "ai-caption",
    "name": "AI Caption Generator",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-comment",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai caption"
  },
  {
    "id": "ai-product",
    "name": "AI Product Description",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-box",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai product"
  },
  {
    "id": "ai-title",
    "name": "AI Title Generator",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-heading",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai title"
  },
  {
    "id": "ai-hashtag",
    "name": "AI Hashtag Generator",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai hashtag"
  },
  {
    "id": "ai-helper",
    "name": "AI Text Helper",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-robot",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai helper"
  },
  {
    "id": "ai-ideas",
    "name": "AI Idea Generator",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-lightbulb",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai ideas"
  },
  {
    "id": "ai-email",
    "name": "AI Email Writer",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-envelope",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai email"
  },
  {
    "id": "ai-study",
    "name": "AI Study Helper",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-book-open",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai study"
  },
  {
    "id": "ai-qa",
    "name": "AI Q&A",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-circle-question",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ai question"
  },
  {
    "id": "image-mirror-text",
    "name": "Image Label Maker",
    "category": "Alat Gambar",
    "description": "Tambah tanda air pada gambar.",
    "kind": "image-watermark",
    "icon": "fa-solid fa-tag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "label"
  },
  {
    "id": "png-transparent-check",
    "name": "Image Type Checker",
    "category": "Alat Gambar",
    "description": "Lihat info gambar.",
    "kind": "image-info",
    "icon": "fa-solid fa-circle-info",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "type"
  },
  {
    "id": "text-wrap",
    "name": "Text Wrapper",
    "category": "Alat Teks",
    "description": "Lipat teks per baris.",
    "kind": "text-wrap",
    "icon": "fa-solid fa-align-justify",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "wrap"
  },
  {
    "id": "remove-punctuation",
    "name": "Remove Punctuation",
    "category": "Alat Teks",
    "description": "Hapus tanda baca.",
    "kind": "no-punct",
    "icon": "fa-solid fa-i-cursor",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "punctuation"
  },
  {
    "id": "initials-generator",
    "name": "Initials Generator",
    "category": "Alat Teks",
    "description": "Buat inisial dari nama.",
    "kind": "initials",
    "icon": "fa-solid fa-signature",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "initials"
  },
  {
    "id": "slug-to-title",
    "name": "Slug to Title",
    "category": "Alat Teks",
    "description": "Ubah slug menjadi judul.",
    "kind": "slug-title",
    "icon": "fa-solid fa-heading",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "slug"
  },
  {
    "id": "json-keys",
    "name": "JSON Key Lister",
    "category": "Alat Pengembang",
    "description": "Daftar kunci JSON.",
    "kind": "json-keys",
    "icon": "fa-solid fa-key",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "json keys"
  },
  {
    "id": "css-unit-converter",
    "name": "CSS Unit Helper",
    "category": "Alat Pengembang",
    "description": "Ubah satuan CSS.",
    "kind": "css-unit",
    "icon": "fa-solid fa-ruler",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "px rem"
  },
  {
    "id": "rgb-to-hsl",
    "name": "RGB to HSL",
    "category": "Alat Pengembang",
    "description": "Ubah format warna.",
    "kind": "color-conv",
    "icon": "fa-solid fa-droplet",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "hsl"
  },
  {
    "id": "number-base",
    "name": "Number Base Converter",
    "category": "Alat Pengembang",
    "description": "Ubah basis bilangan.",
    "kind": "num-base",
    "icon": "fa-solid fa-hashtag",
    "popular": false,
    "newest": false,
    "premium": false,
    "keywords": "binary hex decimal"
  },
  {
    "id": "quote-maker",
    "name": "Quote Maker",
    "category": "Alat Desain",
    "description": "Buat gambar kutipan.",
    "kind": "quote-img",
    "icon": "fa-solid fa-quote-left",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "quote caption"
  },
  {
    "id": "brat-text",
    "name": "Brat Text",
    "category": "Alat Desain",
    "description": "Buat gambar atau GIF tulisan style Brat.",
    "kind": "brat",
    "icon": "fa-solid fa-font",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "brat poster text"
  },
  {
    "id": "nokia-sms",
    "name": "Nokia Message",
    "category": "Alat Desain",
    "description": "Buat kartu pesan gaya Nokia.",
    "kind": "nokia",
    "icon": "fa-solid fa-mobile-screen",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "nokia sms retro"
  },
  {
    "id": "text-to-speech",
    "name": "Text to Speech",
    "category": "Alat Teks",
    "description": "Ubah teks menjadi suara.",
    "kind": "tts",
    "icon": "fa-solid fa-volume-high",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "tts suara"
  },
  {
    "id": "dice-roller",
    "name": "Dice Roller",
    "category": "Utilitas",
    "description": "Lempar dadu.",
    "kind": "dice",
    "icon": "fa-solid fa-dice",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "dadu random"
  },
  {
    "id": "coin-flip",
    "name": "Coin Flip",
    "category": "Utilitas",
    "description": "Lempar koin.",
    "kind": "coin",
    "icon": "fa-solid fa-coins",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "koin"
  },
  {
    "id": "random-pick",
    "name": "Random Picker",
    "category": "Utilitas",
    "description": "Pilih acak dari daftar.",
    "kind": "pick",
    "icon": "fa-solid fa-shuffle",
    "popular": false,
    "newest": true,
    "premium": false,
    "keywords": "acak undian"
  },
  {
    "id": "daily-assistant",
    "name": "Asisten Harian",
    "category": "Alat AI",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-solid fa-comments",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "ai tanya harian"
  },
  {
    "id": "ig-caption",
    "name": "Caption Maker",
    "category": "Media Sosial",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-brands fa-instagram",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "caption ig"
  },
  {
    "id": "wa-status",
    "name": "Status WA Maker",
    "category": "Media Sosial",
    "description": "Tanya jawab harian di perangkat ini, tanpa API.",
    "kind": "ai",
    "icon": "fa-brands fa-whatsapp",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "status wa"
  },
  {
    "id": "color-poster",
    "name": "Color Poster",
    "category": "Alat Desain",
    "description": "Poster tulisan berwarna.",
    "kind": "poster-color",
    "icon": "fa-solid fa-palette",
    "popular": false,
    "newest": true,
    "premium": false,
    "keywords": "poster"
  },
  {
    "id": "checklist-maker",
    "name": "Checklist Maker",
    "category": "Produktivitas",
    "description": "Buat daftar centang.",
    "kind": "checklist",
    "icon": "fa-solid fa-list-check",
    "popular": false,
    "newest": true,
    "premium": false,
    "keywords": "todo checklist"
  },
  {
    "id": "world-clock",
    "name": "World Clock",
    "category": "Tanggal & Waktu",
    "description": "Jam dunia.",
    "kind": "world-clock",
    "icon": "fa-solid fa-earth-asia",
    "popular": false,
    "newest": true,
    "premium": false,
    "keywords": "jam dunia wib"
  },
  {
    "id": "percent-calc",
    "name": "Percent Calculator",
    "category": "Kalkulator",
    "description": "Hitung persen.",
    "kind": "percent",
    "icon": "fa-solid fa-percent",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "diskon persen"
  },
  {
    "id": "ip-lookup",
    "name": "IP Lookup",
    "category": "Alat Pengembang",
    "description": "Cek info IP atau domain.",
    "kind": "ip-lookup",
    "icon": "fa-solid fa-network-wired",
    "popular": false,
    "newest": true,
    "premium": false,
    "keywords": "ip negara"
  },
  {
    "id": "brat-generator",
    "name": "Brat Generator",
    "category": "Alat Desain",
    "description": "Buat gambar atau GIF tulisan style Brat.",
    "kind": "brat",
    "icon": "fa-solid fa-font",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "brat poster"
  },
  {
    "id": "iqc-generator",
    "name": "IQC Generator",
    "category": "Alat Desain",
    "description": "Buat gambar IQC: pesan, operator, jam, baterai.",
    "kind": "iqc",
    "icon": "fa-solid fa-id-card",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "iqc kartu"
  },
  {
    "id": "sertifikat-kocak",
    "name": "Sertifikat Tolol",
    "category": "Alat Desain",
    "description": "Sertifikat iseng.",
    "kind": "sertifikat",
    "icon": "fa-solid fa-award",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "sertifikat tolol meme"
  },
  {
    "id": "fake-dev",
    "name": "FakeDev Card",
    "category": "Alat Desain",
    "description": "Buat kartu profil developer iseng.",
    "kind": "fakedev",
    "icon": "fa-solid fa-user-gear",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "dev profile"
  },
  {
    "id": "fake-lobby",
    "name": "Kartu Lobby Game",
    "category": "Alat Desain",
    "description": "Kartu lobi game iseng.",
    "kind": "lobby",
    "icon": "fa-solid fa-gamepad",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "lobby ff ml pubg"
  },
  {
    "id": "tanya-ustadz",
    "name": "Tanya Pak Ustadz",
    "category": "Utilitas",
    "description": "Jawaban singkat iseng untuk pertanyaan harian.",
    "kind": "ustadz",
    "icon": "fa-solid fa-comments",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "tanya ustadz meme"
  },
  {
    "id": "virus-scan",
    "name": "Cek Tautan / File",
    "category": "Keamanan & Generator",
    "description": "Cek dasar tautan, berkas, atau IP.",
    "kind": "virus-scan",
    "icon": "fa-solid fa-shield-halved",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "virus scan url hash ip"
  },
  {
    "id": "remove-bg",
    "name": "Hapus Background",
    "category": "Alat Gambar",
    "description": "Hapus latar polos pada foto.",
    "kind": "remove-bg",
    "icon": "fa-solid fa-eraser",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "hapus background"
  },
  {
    "id": "ic-browser",
    "name": "IC Browser",
    "category": "Alat Web",
    "description": "Buka halaman lewat tautan di dalam tools.",
    "kind": "ic-browser",
    "icon": "fa-solid fa-globe",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "browser web ic"
  },
  {
    "id": "yt-link",
    "name": "YouTube Link",
    "category": "Media Sosial",
    "description": "Tempel tautan YouTube resmi. Dibuka di YouTube, bukan pengunduh video.",
    "kind": "url-open",
    "icon": "fa-brands fa-youtube",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "youtube url"
  },
  {
    "id": "ig-link",
    "name": "Instagram Link",
    "category": "Media Sosial",
    "description": "Tempel tautan Instagram resmi. Dibuka di Instagram.",
    "kind": "url-open",
    "icon": "fa-brands fa-instagram",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "instagram url"
  },
  {
    "id": "tt-link",
    "name": "TikTok Link",
    "category": "Media Sosial",
    "description": "Tempel tautan TikTok resmi. Dibuka di TikTok.",
    "kind": "url-open",
    "icon": "fa-brands fa-tiktok",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "tiktok url"
  },
  {
    "id": "spotify-link",
    "name": "Spotify Link",
    "category": "Media Sosial",
    "description": "Tempel tautan Spotify resmi. Dibuka di Spotify.",
    "kind": "url-open",
    "icon": "fa-brands fa-spotify",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "spotify url"
  },
  {
    "id": "terabox-link",
    "name": "Terabox Link",
    "category": "Alat Berkas",
    "description": "Tempel tautan Terabox resmi. Dibuka di Terabox.",
    "kind": "url-open",
    "icon": "fa-solid fa-cloud-arrow-down",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "terabox url"
  },
  {
    "id": "fake-tweet",
    "name": "Fake Tweet",
    "category": "Alat VIP",
    "description": "Kartu tweet iseng, bukan Twitter asli.",
    "kind": "tweet-card",
    "icon": "fa-brands fa-x-twitter",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "tweet palsu parody"
  },
  {
    "id": "web-obfuscate",
    "name": "Web Encryption",
    "category": "Alat VIP",
    "description": "Samarkan teks atau HTML.",
    "kind": "obfuscate",
    "icon": "fa-solid fa-lock",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "encrypt obfuscate html"
  },
  {
    "id": "ss-web",
    "name": "Screenshot Web",
    "category": "Alat VIP",
    "description": "Pratinjau screenshot situs.",
    "kind": "ss-web",
    "icon": "fa-solid fa-camera",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "screenshot web ssweb"
  },
  {
    "id": "ml-winrate",
    "name": "ML Winrate",
    "category": "Alat VIP",
    "description": "Hitung winrate Mobile Legends.",
    "kind": "ml-winrate",
    "icon": "fa-solid fa-gamepad",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "ml winrate kalkulator"
  },
  {
    "id": "prompt-pack",
    "name": "Prompt Pack",
    "category": "Alat VIP",
    "description": "Paket prompt menulis dan belajar.",
    "kind": "prompt-pack",
    "icon": "fa-solid fa-lightbulb",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "prompt ai pack"
  },
  {
    "id": "image-pro",
    "name": "Image Compressor Pro",
    "category": "Alat VIP",
    "description": "Kompres gambar di browser.",
    "kind": "image-compress",
    "icon": "fa-solid fa-compress",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "compress pro"
  },
  {
    "id": "domain-pro",
    "name": "IP / Domain Lookup Pro",
    "category": "Alat VIP",
    "description": "Cek info IP atau domain.",
    "kind": "ip-lookup",
    "icon": "fa-solid fa-network-wired",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "ip domain lookup"
  },
  {
    "id": "meta-gen",
    "name": "Meta Tag Generator",
    "category": "Alat VIP",
    "description": "Buat meta tag halaman.",
    "kind": "meta-gen",
    "icon": "fa-solid fa-code",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "seo meta og"
  },
  {
    "id": "md-preview",
    "name": "Markdown Preview",
    "category": "Alat VIP",
    "description": "Pratinjau Markdown.",
    "kind": "markdown",
    "icon": "fa-solid fa-file-lines",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "markdown preview"
  },
  {
    "id": "text-diff",
    "name": "Text Diff",
    "category": "Alat VIP",
    "description": "Bandingkan dua teks.",
    "kind": "diff",
    "icon": "fa-solid fa-not-equal",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "diff banding teks"
  },
  {
    "id": "contrast-check",
    "name": "Contrast Checker",
    "category": "Alat VIP",
    "description": "Cek kontras warna teks dan latar.",
    "kind": "contrast",
    "icon": "fa-solid fa-circle-half-stroke",
    "popular": false,
    "newest": true,
    "premium": true,
    "keywords": "contrast aksesibilitas"
  },
  {
    "id": "og-card",
    "name": "OG Card Maker",
    "category": "Alat VIP",
    "description": "Buat kartu pratinjau tautan.",
    "kind": "og-card",
    "icon": "fa-solid fa-share-nodes",
    "popular": true,
    "newest": true,
    "premium": true,
    "keywords": "og image card"
  },
  {
    "id": "direct-file-dl",
    "name": "Direct File Download",
    "category": "Alat Berkas",
    "description": "Unduh jika tautan langsung ke berkas (.mp4, .mp3, .zip, .pdf).",
    "kind": "url-open",
    "icon": "fa-solid fa-download",
    "popular": true,
    "newest": true,
    "premium": false,
    "keywords": "download url file"
  }
]
};
